In [ ]:
import pandas as pd
df = pd.read_csv('/content/formatted_traffic_data(10).csv')
df.head()

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
0,'Al Sabe,"(24.598009, 46.5957488)","(24.5954907, 46.5925096)",1.34,49.99,0,11.73,Blue
1,110 ممر,"(24.594892, 46.6403652)","(24.571468, 46.5812872)",1.18,34.51,0,8.40,Yellow
2,3rd Roundabout,"(24.6652373, 46.7968369)","(24.6631823, 46.7870053)",0.02,48.38,0,6.09,Blue
3,5399,"(24.43571510000003, 46.8242555)","(24.38574769999997, 46.62209730000001)",-1.13,55.43,2,38.63,Blue
4,AL Hadad,"(24.6927368, 46.7944167)","(24.6437154, 46.7883665)",-0.89,43.45,0,11.44,Blue

In [ ]:
# pd.set_option('display.max_rows', None)
# df.isna().sum()

In [ ]:
df.shape

(429, 8)

In [ ]:
df.describe()

        delay_min   speed_kmh  duration_in_traffic_min  distance_km
count  429.000000  429.000000               429.000000   429.000000
mean     0.417879   41.326340                 0.536131    12.769091
std      1.287082   11.333913                 0.688168    10.142334
min     -3.970000    9.390000                 0.000000     0.120000
25%     -0.360000   33.140000                 0.000000     7.170000
50%      0.070000   39.930000                 0.000000     9.080000
75%      1.020000   47.610000                 1.000000    13.810000
max      6.170000   81.000000                 2.000000    68.050000

In [ ]:
pd.set_option('display.max_rows', None)
df = df[df['distance_km'] >= 5]

In [ ]:
df.shape

(410, 8)

In [ ]:
import ast

df['Start_point'] = df['Start_point'].apply(ast.literal_eval)
df['End_point'] = df['End_point'].apply(ast.literal_eval)


top_left = (24.985496, 46.467449)
bottom_right = (24.609640, 46.928374)

def clean_in_riyadh(row):
  road_start = row['Start_point']
  road_end = row['End_point']
  if (((road_start[0] <= top_left[0]) and (road_start[1] >= top_left[1])) and ((road_start[0] >= bottom_right[0]) and (road_start[1] <= bottom_right[1]))):
    return 'in'

  elif (((road_end[0] <= top_left[0]) and (road_end[1] >= top_left[1])) and((road_end[0] >= bottom_right[0]) and (road_end[1] <= bottom_right[1]))):
    return 'in'

  else:
    return None

df['outside_riyadh'] = df.apply(clean_in_riyadh,axis=1)

In [ ]:
pd.set_option('display.max_rows', None)
df.isna().sum()

road_name                   0
Start_point                 0
End_point                   0
delay_min                   0
speed_kmh                   0
duration_in_traffic_min     0
distance_km                 0
traffic_condition           0
outside_riyadh             97
dtype: int64

In [ ]:
em_va = df[df['outside_riyadh'].isna()]
em_va

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition,outside_riyadh
1,110 ممر,"(24.594892, 46.6403652)","(24.571468, 46.5812872)",1.18,34.51,0,8.40,Yellow,None
3,5399,"(24.43571510000003, 46.8242555)","(24.38574769999997, 46.62209730000001)",-1.13,55.43,2,38.63,Blue,None
11,Afif,"(23.9556658, 42.9571364)","(23.8511982, 42.8685665)",0.83,49.58,1,17.44,Blue,None
15,Al Ahmad Valley,"(24.5590467, 46.70917670000001)","(24.49419, 46.6364446)",-1.07,34.18,1,13.91,Blue,None
19,Al Awali,"(24.5767642, 46.66049169999999)","(24.5428661, 46.5796016)",-0.65,39.71,1,12.24,Blue,None
21,Al Difa,"(24.5983788, 46.8560037)","(24.5735721, 46.8088237)",1.19,45.51,1,19.72,Blue,None
28,Al Hair Road,"(24.5987783, 46.8446611)","(24.3780824, 46.7285093)",-0.00,59.73,2,56.89,Blue,None
31,Al Hazm,"(24.5715387, 46.678946)","(24.5170548, 46.62255260000001)",-0.08,43.62,1,14.61,Blue,None
32,Al Imam S'Aud Bin Abdulaziz Bin Mohammed,"(24.6060597, 46.8495065)","(24.5533825, 46.7744539)",1.43,42.39,2,22.27,Blue,None
36,Al Khazaf,"(24.5848639, 46.686229)","(24.5702727, 46.6453418)",-0.28,43.41,0,6.47,Blue,None
38,Al Madini,"(24.5721571, 46.6495648)","(24.5361463, 46.6337305)",-0.61,29.75,0,6.80,Blue,None
41,Al Merwah,"(24.5564513, 46.6926552)","(24.5248985, 46.6588895)",-1.18,31.85,0,7.70,Blue,None
46,Al Nasser,"(24.6030097, 46.7889715)","(24.5762585, 46.737574)",1.84,40.09,1,10.92,Yellow,None
57,Al Sfar Al Zhabi,"(24.5867759, 46.5475598)","(24.5545491, 46.5427434)",-0.35,49.83,0,9.02,Blue,None
59,Al Sharaf,"(24.6050858, 46.7081197)","(24.5924671, 46.6581626)",-0.04,29.61,1,8.22,Blue,None
60,Al Tawhed,"(24.5602792, 46.6204638)","(24.5516396, 46.609009)",-0.16,52.54,0,6.08,Blue,None
66,Al-Yaqout,"(24.5746754, 46.8277055)","(24.538878, 46.7671967)",-0.09,44.18,1,12.90,Blue,None
70,Bilal Bin Rabah,"(24.5916869, 46.6078033)","(24.5713992, 46.5210757)",-0.82,57.60,0,15.23,Blue,None
71,Binban,"(25.0720744, 46.6302447)","(24.9132569, 46.4564837)",-0.63,65.21,2,40.24,Blue,None
74,Derab Road,"(24.5841406, 46.7067607)","(24.4849312, 46.6219712)",-0.16,63.98,1,17.57,Blue,None
80,Hofuf road,"(25.36624350000002, 49.5905296)","(25.35168369999997, 49.466518)",-0.02,56.27,1,22.16,Blue,None
81,Ibn Al Zaharawi,"(24.4556204, 46.9877982)","(24.439907, 46.972009)",-0.52,59.53,0,9.87,Blue,None
82,Ibn Taymeeyah Road,"(24.5758636, 46.7236754)","(24.5205215, 46.6753627)",-0.84,32.69,1,10.30,Blue,None
99,Malham,"(25.1859133, 46.35646819999999)","(25.1446629, 46.3126088)",0.25,38.05,0,7.63,Blue,None
100,Marat,"(25.09132, 45.5014229)","(25.0467981, 45.4397658)",-0.15,40.78,1,12.05,Blue,None
104,Nahawand,"(24.584978, 46.7962319)","(24.5632022, 46.75510370000001)",0.09,34.86,0,6.16,Blue,None
111,Port Saed Road,"(24.5860316, 46.8252838)","(24.5419287, 46.8010727)",-0.19,35.80,0,9.12,Blue,None
117,Sadir,"(24.5989016, 46.6946822)","(24.5608874, 46.64157160000001)",-0.45,47.39,0,9.41,Blue,None
119,Salbouk Road,"(25.0835778, 46.3639355)","(25.0737049, 46.33389469999999)",-0.79,81.00,1,36.32,Blue,None
122,Shabwa,"(24.5751417, 46.7155194)","(24.5635888, 46.67291059999999)",-1.00,25.09,1,7.38,Blue,None
124,Shoudha Badr,"(24.5726435, 46.7841423)","(24.4951198, 46.6771475)",-1.62,36.25,2,20.70,Blue,None
125,Sinan,"(24.6035359, 46.58912)","(24.5978788, 46.58490219999999)",1.45,51.15,0,10.22,Blue,None
131,Wathilan,"(24.5795234, 46.6952861)","(24.5387215, 46.6758154)",0.14,33.44,0,6.40,Blue,None
139,أبي علي بن الشريف,"(24.5650077, 46.7585045)","(24.5640378, 46.7566151)",0.19,51.93,0,9.73,Blue,None
140,أبي محمد العلاف,"(24.5855703, 46.6457942)","(24.5709221, 46.6072005)",-1.04,31.45,1,8.83,Blue,None
143,أحد,"(24.5075494, 46.6554638)","(24.4722626, 46.6145)",-0.52,48.93,1,17.54,Blue,None
148,أسعد بن سلامة الأنصاري,"(24.5991766, 46.7938116)","(24.5920387, 46.7786878)",-0.04,30.81,0,6.40,Blue,None
149,أشقر بن مروان,"(24.5722899, 46.5752628)","(24.5618795, 46.5210757)",-0.33,39.52,0,7.00,Blue,None
151,أم عمارة,"(24.5634142, 46.7194462)","(24.5321671, 46.6946822)",-0.91,31.85,0,6.30,Blue,None
152,أمين الدين الأربلي,"(24.5935461, 46.691965)","(24.5599237, 46.6842669)",-0.09,33.06,0,7.41,Blue,None
155,إمتداد الطريق الدائري الشرقي - وصلة الخرج),"(24.6385281, 46.9513691)","(24.4952017, 46.7962319)",-3.97,58.51,2,68.05,Blue,None
156,ابن حجر,"(24.5725734, 46.80894)","(24.556628, 46.7768732)",-0.01,44.94,0,7.75,Blue,None
160,الأحوص بن ثعلبة,"(24.603141, 46.681852)","(24.5972235, 46.64926310000001)",-0.97,29.62,0,6.24,Blue,None
161,الأرطاوية,"(26.5400469, 45.3720332)","(26.4802535, 45.3252125)",0.07,48.91,0,7.41,Blue,None
169,الإعتدال,"(24.5554623, 46.7357609)","(24.5222612, 46.7103848)",-0.34,31.19,0,7.72,Blue,None
172,الإمام بن جرير,"(24.6083, 46.7791414)","(24.6057216, 46.77657079999999)",0.87,44.20,0,7.23,Blue,None
173,الإمام مسلم,"(24.5556039, 46.7768732)","(24.4720865, 46.66932689999999)",-1.75,41.31,2,33.84,Blue,None
175,الباجي,"(24.5646125, 46.6341828)","(24.5622561, 46.6325054)",-0.36,54.66,0,6.75,Blue,None
182,الترمذي,"(24.5759293, 46.7164256)","(24.5533497, 46.6946822)",-1.07,31.69,0,6.56,Blue,None
183,التصنيع,"(24.585532, 46.7430136)","(24.5571824, 46.712801)",-0.07,43.33,0,6.13,Blue,None
186,الثوابية,"(24.5991424, 46.7285093)","(24.5646728, 46.6801919)",0.24,39.33,0,7.70,Blue,None
187,الجادعي,"(24.5956024, 46.5924343)","(24.573362, 46.5499681)",-0.24,32.62,0,7.67,Blue,None
197,الخليفة الناصر لدين الله,"(24.5849552, 46.6343336)","(24.5669688, 46.6210667)",0.20,36.23,0,6.54,Blue,None
203,الزلفي,"(26.3641879, 44.9210358)","(26.213051, 44.75521089999999)",0.31,56.06,2,28.43,Blue,None
208,السمح بن مالك,"(24.5897615, 46.8567756)","(24.5714292, 46.8252838)",0.62,41.13,0,6.24,Blue,None
209,السوفه العليا,"(24.5269302, 46.9186431)","(24.5228396, 46.9131466)",-0.74,60.37,0,14.45,Blue,None
210,السويدي العام,"(24.6055933, 46.7067607)","(24.5807802, 46.6572575)",0.35,44.77,0,8.12,Yellow,None
219,الصحراوي,"(24.5799692, 46.7093277)","(24.5682164, 46.65605069999999)",-0.39,40.53,0,8.57,Blue,None
220,الصفاة,"(24.5489714, 46.8979572)","(24.4841557, 46.8338156)",-1.00,58.79,1,25.56,Blue,None
243,القطار,"(24.6020912, 46.660878)","(24.5873951, 46.61744909999999)",0.10,28.54,0,6.02,Blue,None
247,المجاردة,"(24.5676496, 46.7542724)","(24.5644145, 46.7483026)",0.24,59.41,0,14.30,Blue,None
249,المدارة,"(24.586451, 46.6956635)","(24.5521282, 46.6635087)",-0.36,50.43,0,8.58,Blue,None
250,المزاحمية,"(24.5279793, 46.349945)","(24.4012757, 46.1845023)",-1.38,63.84,2,46.38,Blue,None
251,المسلمة,"(24.5839929, 46.66630929999999)","(24.5486525, 46.6231017)",-0.41,34.29,0,8.80,Blue,None
267,الوليد بن عبدالملك,"(24.5969246, 46.5836972)","(24.5848388, 46.5355198)",-1.01,32.12,0,6.90,Blue,None
270,الياقوت,"(24.5508047, 46.7817122)","(24.5397372, 46.7647779)",-1.02,32.95,0,6.82,Blue,None
271,بنت المعتمد,"(24.5963613, 46.5925096)","(24.5935194, 46.5903252)",1.24,49.32,0,11.29,Orange,None
275,بيروت,"(33.9161091, 35.5416362)","(33.8623275, 35.4669284)",-0.75,31.82,1,9.89,Blue,None
277,ثرمداء,"(25.1382917, 45.5142975)","(25.1075959, 45.4714681)",-0.34,44.87,0,6.58,Blue,None
280,جبل شبرى,"(24.5965515, 46.6945024)","(24.5611161, 46.6416094)",-0.99,42.85,0,7.79,Blue,None
286,جلاجل,"(25.712693, 45.4933548)","(25.661024, 45.4375648)",-0.77,68.37,1,19.53,Blue,None
287,جنين,"(24.6060922, 46.6017757)","(24.5748326, 46.5861072)",-1.26,29.09,0,6.34,Blue,None
298,خديجة بنت خويلد,"(24.6042471, 46.6041867)","(24.5749012, 46.5210757)",-0.70,58.83,1,16.39,Blue,None
301,دمنهور,"(24.5460718, 46.6813993)","(24.4659922, 46.630715)",0.37,40.29,1,19.53,Blue,None
302,ديراب,"(24.5384507, 46.6451102)","(24.4823168, 46.593364)",-0.97,42.45,1,12.49,Blue,None
306,روض الجواء,"(24.5584172, 46.7774781)","(24.5511378, 46.7647779)",-0.32,41.56,0,8.22,Blue,None
319,شارع أمنة بنت أبي القاسم,"(24.5638385, 46.75827779999999)","(24.5624883, 46.7573709)",0.05,50.63,0,9.58,Blue,None
324,شارع الأمير متعب بن عبدالله بن عبدالعزيز,"(24.756016, 46.941659)","(24.5938452, 46.8495065)",-2.00,55.46,2,29.90,Blue,None
347,شارع معاذ بن جبل,"(24.6049838, 46.7786878)","(24.5916431, 46.7702204)",1.30,37.21,0,6.98,Blue,None
351,شجوى,"(24.5840971, 46.6394604)","(24.5739943, 46.5963138)",1.04,32.03,0,6.82,Yellow,None
354,ضرما,"(24.6769698, 46.2431716)","(24.5575846, 46.0679053)",-0.90,45.75,2,24.35,Blue,None
359,طريق الأمير مقرن بن عبد العزيز، عين البراحة,"(24.7944098, 43.86506079999999)","(24.743728, 43.7278605)",-0.10,47.43,1,16.39,Blue,None
369,طريق بنبان,"(25.0416181, 46.6801919)","(25.0127506, 46.5873123)",-0.04,76.42,0,10.30,Blue,None
371,طريق حوطة بني تميم - الرياض,"(24.43326210000003, 46.8798891)","(24.30150119999998, 46.834662)",-0.67,56.82,2,40.65,Blue,None
373,طريق ديراب,"(24.58994840000003, 46.7055477)","(24.43446389999998, 46.6103736)",2.36,53.96,2,29.67,Yellow,None
377,طيبة,"(24.5735721, 46.8649294)","(24.5099959, 46.7958078)",-0.56,38.87,1,18.51,Blue,None
381,عبدالقادر صابر,"(24.576561, 46.8059896)","(24.5605395, 46.7744539)",-0.17,41.13,0,7.32,Blue,None
389,عفيف - الحوميات,"(23.0844693, 42.9125976)","(23.0471961, 42.8549193)",0.11,48.28,0,7.36,Blue,None
396,قصور آل مقبل,"(24.5783487, 46.4275359)","(24.4752254, 46.2864304)",-0.72,64.99,2,57.71,Blue,None
397,كروان السويدي,"(24.6046188, 46.70659879999999)","(24.5769133, 46.6519375)",-0.65,37.91,0,7.79,Blue,None
398,مارية القبطية,"(24.5974473, 46.592133)","(24.5888401, 46.5861072)",1.15,47.91,0,12.28,Blue,None
405,معادي,"(24.5913209, 46.6946822)","(24.541271, 46.65001720000001)",0.02,47.06,0,10.35,Blue,None
409,ممر حسين الحبشي,"(24.5999842, 46.5972554)","(24.5965173, 46.592133)",1.53,51.34,0,11.24,Blue,None
415,نجم الدين أبي حامد,"(24.5902846, 46.670534)","(24.5367663, 46.4970116)",-1.52,61.30,2,30.87,Blue,None
416,نمار,"(24.586135, 46.7052896)","(24.5601965, 46.6710482)",0.76,48.00,0,9.24,Blue,None
417,هيت,"(24.5176659, 47.022965)","(24.4388512, 46.9356208)",-0.28,27.29,1,11.62,Blue,None
418,وادي أيروان,"(24.5792541, 46.6886441)","(24.5754641, 46.6838141)",-0.91,37.82,0,6.34,Blue,None

In [ ]:
df.dropna(inplace=True)

In [ ]:
df.drop(columns=['outside_riyadh'],inplace=True)

In [ ]:
df.shape

(313, 8)

In [ ]:
df[df['delay_min'] < 0]

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
4,AL Hadad,"(24.6927368, 46.7944167)","(24.6437154, 46.7883665)",-0.89,43.45,0,11.44,Blue
6,Abdullah Bin Omar,"(24.750219, 46.8446611)","(24.7078712, 46.815598)",-0.71,38.38,1,13.08,Blue
8,Abi Safwon,"(24.9122469, 46.8107557)","(24.903784, 46.7938116)",-0.22,55.74,0,7.64,Blue
9,Abi Taher Ibn Al Salam,"(24.722725, 46.8276552)","(24.692795, 46.7947917)",-1.16,28.81,0,6.31,Blue
13,Aka,"(24.6936072, 46.8313384)","(24.6565883, 46.75510370000001)",-1.03,39.23,1,12.04,Blue
25,Al Ghadir,"(24.7862846, 46.6684286)","(24.7610666, 46.640876)",-0.27,36.17,0,8.69,Blue
29,Al Hamla,"(24.7913163, 46.77653309999999)","(24.7598942, 46.730632)",-0.29,41.17,0,9.45,Blue
34,Al Janadriyah,"(24.9445838, 46.9975312)","(24.7875365, 46.84589709999999)",-0.07,73.29,2,40.18,Blue
35,Al Jazeera Al Khuzra,"(24.6860722, 46.8153462)","(24.6433178, 46.7776658)",-1.11,41.18,0,10.44,Blue
37,Al Khozama,"(24.7363514, 46.6231959)","(24.691285, 46.5685328)",-0.26,45.73,1,14.24,Blue
39,Al Masrouh,"(24.6219828, 46.7653843)","(24.5942887, 46.7283912)",-0.86,33.36,0,8.75,Blue
40,Al Massaif,"(24.7775434, 46.6947278)","(24.7535293, 46.6684286)",-0.67,39.39,0,7.91,Blue
43,Al Nadwah,"(24.8278719, 46.9278255)","(24.7727852, 46.8616075)",-0.38,28.81,1,13.35,Blue
50,Al Rafaih,"(24.6504946, 46.6769391)","(24.6252127, 46.6438333)",-0.18,31.75,0,7.37,Blue
51,Al Rakb,"(24.7092213, 46.81680859999999)","(24.6843684, 46.7703716)",-0.20,35.65,0,8.83,Blue
53,Al Remal,"(24.9623711, 46.8511917)","(24.8228584, 46.75764179999999)",-0.49,52.74,1,23.56,Blue
55,Al Sahel Valley,"(24.866488, 46.815598)","(24.8287479, 46.7938116)",-0.62,44.91,0,8.04,Blue
62,Al Thuraya,"(24.7651064, 46.75570829999999)","(24.7388652, 46.7233733)",-0.15,37.12,0,7.03,Blue
67,Ariha,"(24.7064561, 46.77233709999999)","(24.6560661, 46.7309264)",-0.20,31.65,1,10.57,Blue
68,As Salah,"(24.8258293, 46.9101143)","(24.7908938, 46.8919243)",-0.36,26.78,1,7.75,Blue
75,Dhalam,"(24.8320047, 46.6934745)","(24.8206771, 46.66932689999999)",-0.35,48.47,0,10.78,Blue
79,Farsan,"(24.8359023, 46.6910592)","(24.8311855, 46.6812483)",-0.26,54.51,0,7.14,Blue
83,Ibraheem Bin Abdulsalam,"(24.6593747, 46.7057037)","(24.5973701, 46.6523551)",-0.07,33.62,1,11.99,Blue
85,Irqah,"(24.7093091, 46.6160267)","(24.6686628, 46.4822893)",-0.19,49.04,1,17.91,Blue
86,Ismail Al Andulus,"(24.7568426, 46.8027447)","(24.7302837, 46.7745554)",-0.25,38.53,0,6.72,Blue
88,Jzr Al Khaleej,"(24.7968653, 46.8295247)","(24.7568426, 46.77653309999999)",-0.25,28.05,1,9.85,Blue
89,Karachi,"(24.7602337, 46.601173)","(24.7539594, 46.5975568)",-2.23,39.25,0,5.88,Blue
112,Prince Ahmed Bin Abdulaziz,"(24.644358, 46.6463975)","(24.6263283, 46.5861072)",-0.59,41.04,0,8.11,Blue
113,Prince Sultan Bin Abdul Aziz,"(24.78070620000002, 46.5690375)","(24.74708999999998, 46.528985)",-0.11,41.92,0,8.20,Blue
120,Second Ring Road,"(24.7607903, 46.8688931)","(24.6605258, 46.8446611)",-0.22,53.01,1,15.10,Blue
123,Shaheed Al Din Thum Al Watan Talal Abdulrahman...,"(24.7338302, 46.5931876)","(24.730017, 46.5900239)",-0.18,55.22,0,8.07,Blue
127,Taiba,"(24.6511266, 46.5692391)","(24.6237563, 46.549366)",-1.04,30.17,0,7.40,Blue
128,Tareq Bin Zaid Road,"(24.7469689, 46.8410273)","(24.706146, 46.8107557)",-0.46,23.78,1,7.49,Blue
130,Umm Al Hamam,"(24.7124471, 46.6657058)","(24.6705468, 46.6488106)",-0.37,32.12,0,7.32,Blue
135,أبو عبيدة عامر بن الجراح,"(24.6956725, 46.8591989)","(24.6619895, 46.7841318)",-1.05,39.31,1,14.70,Blue
137,أبي الفتوح بن أبي الفوارس,"(24.7233106, 46.82316489999999)","(24.6967577, 46.7762684)",-1.23,27.47,0,7.00,Blue
142,أبي نصر الفارابي,"(24.6557667, 46.8913181)","(24.6429911, 46.8834379)",-2.23,52.48,1,25.79,Blue
146,أسامة بن حارثة الكلبي,"(24.7750098, 46.6162433)","(24.7561845, 46.6053922)",-1.03,34.77,0,6.00,Blue
147,أسد السنة,"(24.6580379, 46.7768732)","(24.6289546, 46.7623591)",-0.40,37.33,0,9.06,Blue
153,إبراهيم آل الشيخ,"(24.8351449, 46.6922669)","(24.8296699, 46.6819982)",-0.35,53.71,0,6.95,Blue
154,إسماعيل البغدادي,"(24.7589695, 46.8053088)","(24.7281493, 46.7811073)",-0.85,34.08,0,6.00,Blue
163,الأشبيلي,"(24.8093433, 46.8181123)","(24.776426, 46.7663688)",-0.38,43.77,0,10.78,Blue
165,الأمير سعود بن عبدالله بن جلوي,"(24.8687954, 46.6632918)","(24.840795, 46.6053922)",-0.69,56.99,0,14.44,Blue
170,الإمام أبي حنيفة,"(24.6353085, 46.6946822)","(24.5899618, 46.60298119999999)",-0.56,36.86,1,14.02,Blue
179,البشائر,"(24.7139597, 46.8227108)","(24.6825958, 46.790484)",-0.54,34.82,0,7.62,Blue
184,التعاون,"(24.785114, 46.7126813)","(24.7611094, 46.6864381)",-0.34,39.82,0,6.71,Blue
188,الجبل الأبيض,"(24.7987395, 46.6509222)","(24.7389743, 46.6023784)",-0.59,46.81,0,12.61,Blue
196,الخضر النيسابوري,"(24.7628082, 46.7662896)","(24.7368424, 46.7121969)",-0.29,34.36,0,9.11,Blue
198,الخيم,"(24.6615875, 46.6578609)","(24.6092857, 46.5951461)",-0.69,38.99,1,14.67,Blue
199,الدائري الثاني,"(24.7607903, 46.8688931)","(24.655751, 46.8446611)",-0.34,57.74,1,17.35,Blue
200,الرافدة,"(24.7758526, 46.8313384)","(24.7477668, 46.8253595)",-0.53,35.31,0,5.17,Blue
205,السعيد,"(24.7499138, 46.64398449999999)","(24.739142, 46.6289058)",-0.01,41.48,0,5.86,Blue
207,السماحة,"(24.6255002, 46.6893988)","(24.5726548, 46.6453418)",-0.89,38.14,1,12.46,Blue
211,الشبارقة,"(24.7619765, 46.8342524)","(24.7252447, 46.7944167)",-0.31,49.17,0,7.66,Blue
212,الشرق,"(24.9968329, 47.0206171)","(24.8395321, 46.8220266)",-0.47,76.59,1,32.18,Blue
214,الشموس,"(24.7190346, 46.8223324)","(24.7058256, 46.7774781)",-0.75,27.82,0,6.16,Blue
218,الشيخ محمد بن عبدالوهاب,"(24.78522760000002, 46.5545655)","(24.75757079999997, 46.5283655)",-0.19,43.58,0,8.45,Blue
223,الضوء,"(24.8929433, 46.84344979999999)","(24.8699569, 46.8047036)",-0.75,72.14,0,17.62,Blue
224,الطحاوي,"(24.8312822, 46.61202309999999)","(24.8279201, 46.6059196)",-0.89,46.81,0,8.64,Blue
229,العزايزه,"(24.6123559, 46.8088237)","(24.5613804, 46.7373393)",-0.12,43.23,1,19.19,Blue
230,العقيق,"(24.7938496, 46.6473255)","(24.7535059, 46.6128186)",-0.23,49.04,0,7.66,Blue
231,العوفي,"(24.9387209, 46.941659)","(24.8809379, 46.8907119)",-0.41,40.44,1,19.37,Blue
233,الغاط,"(24.7814243, 46.7025329)","(24.7691874, 46.6777773)",-0.16,45.07,0,6.34,Blue
234,الغوازي,"(24.7125874, 46.8425413)","(24.7049446, 46.7981984)",-0.47,31.35,0,7.15,Blue
236,الفضل اليزيدي,"(24.7509366, 46.8228622)","(24.744356, 46.7662896)",-0.81,32.12,1,9.03,Blue
245,الكهف,"(24.7553203, 46.8216514)","(24.6973906, 46.81317680000001)",-0.38,31.87,1,9.76,Blue
246,الكواكب,"(24.6976613, 46.8567756)","(24.6748499, 46.8422385)",-0.54,52.40,0,11.16,Blue
256,الملد,"(24.79773910000002, 46.5814561)","(24.75346339999997, 46.54661769999999)",-0.63,42.28,0,10.21,Blue
259,الملك فهد,"(24.7535293, 46.68524009999999)","(24.7278467, 46.65562389999999)",-0.19,35.55,0,7.50,Blue
261,النرجس,"(24.9789363, 46.7011156)","(24.8102943, 46.5886374)",-0.16,62.62,2,35.36,Blue
262,النفل,"(24.7937761, 46.6864381)","(24.769956, 46.6602666)",-0.18,42.29,0,6.37,Blue
263,النهضة,"(24.7812165, 46.8412932)","(24.740026, 46.7902745)",-0.21,45.78,0,12.36,Blue
272,بنها,"(24.6111439, 46.8373937)","(24.5987364, 46.8204406)",-0.36,48.01,0,11.67,Blue
273,بياض,"(24.8079552, 46.7655526)","(24.7732969, 46.7623591)",-0.09,26.04,0,5.56,Blue
274,بيدة,"(24.6137046, 46.6878894)","(24.5886539, 46.6349367)",-0.56,28.80,1,8.50,Blue
278,ثمينة,"(24.8090501, 46.763115)","(24.772079, 46.71129089999999)",-0.16,36.83,0,9.39,Blue
279,جاكارتا,"(24.7186837, 46.8567756)","(24.6891738, 46.8543525)",-0.01,32.67,0,6.03,Blue
281,جبل طويق,"(24.6116569, 46.59702069999999)","(24.5242615, 46.43972429999999)",-0.78,72.31,1,24.55,Blue
283,جبل مرخة,"(24.7425462, 46.8543525)","(24.7205517, 46.8171112)",-0.65,32.28,1,9.75,Blue
285,جرير,"(24.6883175, 46.76049620000001)","(24.6661834, 46.7409476)",-0.09,31.56,0,6.02,Blue
295,حمزة الاركوبي,"(24.6172233, 46.6463975)","(24.5561234, 46.6017757)",-0.40,39.66,1,14.65,Blue
299,خيران,"(24.7055697, 46.8065192)","(24.6888833, 46.76024289999999)",-0.15,30.04,0,7.10,Blue
305,رقوان,"(24.627163, 46.6096871)","(24.5744531, 46.56547459999999)",-0.06,36.21,1,15.43,Blue
309,ساحل,"(24.6390092, 46.737574)","(24.615552, 46.7251859)",-0.02,21.76,1,5.89,Blue
311,سعد بن أبي وقاص,"(24.745241, 46.83618260000001)","(24.7044208, 46.805914)",-0.53,24.76,1,7.40,Blue
312,سلمان الفارسي,"(24.7814775, 46.8204406)","(24.750219, 46.7962319)",-0.22,41.36,0,8.43,Blue
313,سليمان بن عبدالله آل الشيخ,"(24.7384386, 46.64157160000001)","(24.7046701, 46.6078033)",-0.23,38.11,0,9.63,Blue
316,شارع أبوهريرة,"(24.754436, 46.8543525)","(24.7157648, 46.8249811)",-0.69,43.14,1,12.44,Blue
317,شارع أبي الأسود الدؤلي,"(24.7586531, 46.8591989)","(24.717821, 46.8295219)",-0.01,40.24,1,13.87,Blue
320,شارع ابن حزم,"(24.6193955, 46.6053922)","(24.5917193, 46.5800822)",-0.86,40.75,0,10.61,Blue
325,شارع الامير بندر بن عبد العزيز,"(24.7941059, 46.850718)","(24.7457271, 46.7720347)",-0.85,43.50,1,13.78,Blue
329,شارع الشيخ عبدالله بن جبرين,"(24.8353917, 46.6102146)","(24.8202052, 46.5812872)",-0.88,52.42,0,11.09,Blue
333,شارع الوقار,"(24.7854313, 46.7620568)","(24.7611366, 46.70917670000001)",-0.52,38.75,1,11.20,Blue
334,شارع حفصة بنت عمر,"(24.7546817, 46.8071244)","(24.721463, 46.7575221)",-0.43,38.23,0,9.78,Blue
335,شارع ريحانة بنت زيد,"(24.9025533, 46.6512239)","(24.8838705, 46.6102146)",-1.06,46.47,0,12.13,Blue
337,شارع شبه الجزيرة,"(24.7095964, 46.91254010000001)","(24.60379, 46.815598)",-0.20,54.63,2,31.96,Blue
340,شارع عبدالرحمن بن حمود السميط,"(24.8518274, 46.60298119999999)","(24.8424923, 46.5836972)",-0.86,44.20,0,6.71,Blue
341,شارع عبدالملك بن سكينة,"(24.7357296, 46.64157160000001)","(24.6960973, 46.6081801)",-0.12,46.32,0,9.07,Blue
345,شارع فاطمة الزهراء,"(24.6907085, 46.76296380000001)","(24.6546898, 46.72730079999999)",-1.50,30.88,1,9.32,Blue
348,شارع منصور الحازمي,"(24.8953296, 46.6391588)","(24.8890564, 46.6355399)",-0.64,43.84,0,6.88,Blue
350,شبيب الليثي,"(24.7572653, 46.7708252)","(24.7212289, 46.7460358)",-0.02,29.54,0,7.91,Blue
358,طريق الأمير فيصل بن بندر بن عبدالعزيز,"(25.0006575, 46.70917670000001)","(24.8068767, 46.5833959)",-0.94,63.61,2,41.10,Blue
364,طريق السلطان قابوس بن سعيد,"(24.822224, 46.8640458)","(24.7816156, 46.83012739999999)",-0.78,37.87,0,8.21,Blue
372,طريق خزام,"(25.0520962, 46.8071244)","(24.8801496, 46.6994378)",-1.16,63.25,2,42.59,Blue
378,عائشة بنت أبي بكر,"(24.6178467, 46.670534)","(24.5647352, 46.6319212)",-0.15,28.70,1,9.87,Blue
380,عباد بن الحارث,"(24.6779043, 46.7780829)","(24.6666887, 46.7696157)",-0.21,39.11,0,6.80,Blue
384,عبدالملك بن العباس,"(24.6525323, 46.5210757)","(24.6411795, 46.5066359)",-0.22,43.01,0,8.88,Blue
385,عثمان الضبي,"(24.6710714, 46.7078177)","(24.6034634, 46.6580872)",-0.56,32.73,1,12.93,Blue
388,عطية بن جنادة,"(24.7606712, 46.7874591)","(24.7520107, 46.747547)",-0.14,28.97,0,6.50,Blue
392,عمير بن سنان بن عرفطة,"(24.6691819, 46.5186688)","(24.6289579, 46.4705546)",-1.04,46.53,0,7.61,Blue
394,قتادة,"(24.6564596, 46.7082707)","(24.6025389, 46.6589169)",-0.25,33.88,1,11.53,Blue
400,محايدة,"(24.6584052, 46.5861072)","(24.6533337, 46.5855047)",-0.05,40.94,0,6.16,Blue
402,محمد بن البشير ألازهري,"(24.6760787, 46.8410273)","(24.6631189, 46.81801919999999)",-0.29,40.10,0,6.77,Blue
406,مليجة,"(24.6853803, 46.8428441)","(24.6294166, 46.7726395)",-0.49,44.36,1,13.01,Blue
407,ممر الجوابرة,"(24.7358359, 46.6682707)","(24.7026367, 46.632072)",-0.47,33.14,0,7.05,Blue
408,ممر النظيم,"(24.9526781, 47.0577478)","(24.7695123, 46.8615818)",-1.87,50.92,2,31.83,Blue
411,ممرالأحقاب,"(24.7326658, 46.82377030000001)","(24.675455, 46.7805024)",-0.57,36.38,1,13.76,Blue
412,منفوحة,"(24.6109435, 46.7373393)","(24.587994, 46.7195843)",-0.01,32.20,0,6.07,Blue
413,منيفة,"(24.7287144, 46.6720429)","(24.6888318, 46.6388195)",-0.51,30.75,1,8.31,Blue
424,وادي درعة,"(24.6628532, 46.8264947)","(24.6359111, 46.7684062)",-0.86,34.90,0,8.52,Blue

In [ ]:
# df.drop('Distance_Cluster', axis=1, inplace=True) # Drop the 'Distance_Cluster' column from the DataFrame. Use axis=1 to specify that you're dropping a column.

In [ ]:
df = df[df['delay_min'] > 0]
df.shape

(192, 8)

In [ ]:
df

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
2,3rd Roundabout,"(24.6652373, 46.7968369)","(24.6631823, 46.7870053)",0.02,48.38,0,6.09,Blue
5,Abdulaziz Al Fereh,"(24.6746147, 46.73819719999999)","(24.586689, 46.6373493)",0.96,33.72,2,19.60,Blue
7,Abi Hasain Al Hanbali,"(24.8022123, 46.6638953)","(24.7837499, 46.6243831)",0.10,34.61,0,8.82,Blue
10,Abu Thabit,"(24.7534692, 46.8495065)","(24.7095964, 46.815598)",0.09,47.17,1,14.76,Blue
12,Airport Road,"(24.9974697, 46.7381783)","(24.7791458, 46.6512239)",0.73,51.72,2,36.60,Blue
14,Al Abbas Al Rashidi St.,"(24.6923431, 46.8495065)","(24.5915754, 46.7865516)",2.29,45.69,2,22.51,Blue
16,Al Ammar,"(24.7286847, 46.6826067)","(24.6936181, 46.6457942)",0.26,27.17,0,6.96,Blue
17,Al Anbari,"(24.7330062, 46.7599405)","(24.6821831, 46.74875600000001)",0.20,36.43,0,8.36,Blue
18,Al Ataya,"(24.7536362, 46.7623591)","(24.7333674, 46.7088747)",0.33,38.30,0,7.23,Blue
20,Al Basham St.,"(24.7493703, 46.8243757)","(24.6834516, 46.7679526)",1.67,43.85,1,13.81,Yellow
22,Al Falah,"(24.8091397, 46.7223406)","(24.785114, 46.6960814)",0.38,39.93,0,9.20,Blue
23,Al Farish,"(24.7891692, 46.7170297)","(24.7480719, 46.6687234)",0.75,48.15,0,11.34,Blue
24,Al Farzdaq Street,"(24.6870478, 46.7430136)","(24.6048722, 46.7188421)",0.75,32.11,2,16.02,Blue
26,Al Ghareeb,"(24.7235842, 46.7901815)","(24.6767355, 46.7497383)",0.24,37.55,1,10.71,Blue
27,Al Ghazaleh Path,"(24.6578442, 46.7031368)","(24.6255367, 46.6812483)",0.77,38.37,0,6.74,Blue
30,Al Hareth,"(24.8013768, 46.7484915)","(24.742101, 46.7052507)",2.19,35.90,1,11.40,Blue
33,Al Jabour,"(24.6440511, 46.7655337)","(24.6101493, 46.7170297)",2.12,28.89,1,10.52,Blue
42,Al Muhareb,"(24.6431497, 46.7285093)","(24.5460354, 46.6476041)",4.37,42.34,2,20.86,Blue
44,Al Nahdha road,"(24.7084691, 46.7865516)","(24.6251442, 46.7430136)",1.39,49.14,1,18.72,Blue
45,Al Naqeel,"(24.7610666, 46.65562389999999)","(24.7238296, 46.5904416)",0.58,49.73,1,15.05,Blue
47,Al Olaya,"(24.7165527, 46.7035117)","(24.6682398, 46.66354519999999)",1.91,40.26,1,12.85,Blue
48,Al Rabeah Aljarmi,"(24.7391318, 46.7587313)","(24.6933374, 46.7555571)",0.40,39.11,0,9.08,Blue
49,Al Raed,"(24.7205795, 46.6541829)","(24.694263, 46.62321)",0.90,36.45,0,8.23,Blue
52,Al Rawdh,"(24.7532343, 46.7870871)","(24.7145113, 46.7488715)",0.53,39.76,0,9.40,Yellow
54,Al Rumh,"(24.7587914, 46.6898516)","(24.7200682, 46.67294829999999)",0.30,34.37,0,7.88,Blue
56,Al Sanya al Baida,"(24.7310537, 46.84344979999999)","(24.6808089, 46.7578244)",0.67,36.20,1,14.23,Yellow
58,Al Shaba'Niah,"(24.8519613, 46.805914)","(24.7657102, 46.7212587)",1.93,51.08,1,18.83,Blue
61,Al Thoumamah Rd,"(24.9378398, 46.815598)","(24.7479639, 46.6319212)",1.30,56.96,2,34.07,Blue
63,Al Ward,"(24.6770813, 46.5903299)","(24.6277137, 46.54394749999999)",1.87,36.39,1,11.98,Blue
64,Al-Fajar,"(24.8180188, 46.6660075)","(24.8126, 46.6558999)",1.17,46.88,0,7.57,Yellow
69,Atia,"(24.7736461, 46.7222027)","(24.7524547, 46.6826067)",0.75,44.05,0,6.01,Yellow
73,Dammam Road,"(24.9568714, 47.0291162)","(24.7886798, 46.7188421)",0.67,71.85,2,47.04,Blue
76,Discovery Blvd,"(24.7659472, 46.6391588)","(24.7607916, 46.636143)",0.41,45.30,0,9.95,Blue
77,East Ring Road,"(24.7921447, 46.805914)","(24.6224894, 46.7188421)",4.97,46.10,2,35.51,Blue
78,FAHHAD MOHAMMAD AL JFIRAN STREET,"(24.68896, 46.76417319999999)","(24.6840036, 46.7132541)",1.14,30.06,1,8.91,Blue
84,Imam Malik Road,"(24.8506483, 46.7188421)","(24.7825477, 46.56863670000001)",2.42,52.24,1,22.28,Yellow
87,Jeddah Road,"(24.6942703, 46.64157160000001)","(24.5263166, 46.4387046)",2.34,75.92,2,52.83,Blue
90,Khurais Road,"(24.946473, 46.9999471)","(24.7106093, 46.7623591)",3.50,70.07,2,41.16,Blue
91,King Abdul Aziz Road,"(24.9996923, 46.7285093)","(24.6422095, 46.5499681)",1.77,60.83,2,57.52,Blue
92,King Abdulaziz,"(24.7427455, 46.7450497)","(24.6935528, 46.6929946)",2.52,36.14,1,11.75,Yellow
93,King Abdullah Road,"(24.801193, 46.8204406)","(24.6968763, 46.6222727)",4.19,57.52,1,25.50,Blue
94,King Salman Road,"(24.97692050000003, 46.7237318)","(24.79621499999998, 46.5574488)",0.95,68.24,2,42.18,Blue
95,King Saud,"(24.6933354, 46.7188421)","(24.638759, 46.6457942)",3.14,40.43,1,13.38,Blue
96,Laban Valley,"(24.6575726, 46.6508675)","(24.6016845, 46.563363)",2.98,51.00,1,21.29,Blue
97,Maan Bin Ows,"(24.6320336, 46.8010727)","(24.6273961, 46.7913915)",1.52,45.83,0,7.16,Blue
98,Makkah al-Mukarramah Road,"(24.7201491, 46.7671967)","(24.6656897, 46.6367462)",3.89,48.51,1,16.70,Blue
101,Masafi,"(24.8249208, 46.7484538)","(24.7987016, 46.7084972)",0.05,39.30,0,7.17,Blue
102,Mohamed Ibn Hamd Ibn Faris,"(24.6679326, 46.7478493)","(24.6359973, 46.7285093)",2.46,26.47,0,6.54,Blue
103,Mohammed Ali Jinnah,"(24.8148754, 46.7986522)","(24.7545582, 46.6995133)",0.76,47.61,1,17.84,Blue
105,No.2,"(24.8184527, 46.6657058)","(24.8152541, 46.6584643)",0.76,48.81,0,6.64,Blue
106,No.509,"(24.9625832, 46.7285093)","(24.699414, 46.574058)",1.40,69.78,2,48.18,Blue
107,Northern Ring Road,"(24.9560346, 47.01452949999999)","(24.7258755, 46.5830947)",2.80,77.95,2,55.00,Blue
108,Olaya Road,"(24.8302126, 46.6995133)","(24.6639052, 46.612626)",2.69,60.91,2,38.20,Blue
109,Omar Al Hajeb,"(24.7854632, 46.8028881)","(24.760707, 46.7590336)",0.37,32.06,0,6.34,Blue
110,Othman Bin Affan Road,"(24.8540833, 46.7285093)","(24.7410088, 46.670534)",4.22,52.66,1,19.09,Blue
114,Qaha,"(24.8094773, 46.7508718)","(24.7984307, 46.712499)",0.56,45.99,0,7.06,Blue
115,Raghdan,"(24.6722289, 46.7345617)","(24.6388126, 46.7019289)",1.46,24.44,1,6.51,Blue
116,Sabta,"(24.76491, 46.6699305)","(24.7191642, 46.6578609)",1.80,41.48,0,7.75,Blue
118,Saeed Bin Amer,"(24.7272521, 46.7727151)","(24.6793498, 46.7581267)",0.12,37.10,0,8.82,Blue
121,Shab uldin Al taj,"(24.78133100000002, 46.6595165)","(24.73717459999997, 46.5755256)",0.82,55.24,0,12.46,Blue
126,Soukh Thi Al Mjaz,"(24.6817475, 46.7546277)","(24.6475414, 46.716127)",0.74,29.46,1,8.52,Blue
129,Tariq Bin Shabab,"(24.6226251, 46.7671967)","(24.5785679, 46.7430136)",1.31,39.14,0,10.27,Blue
132,Western Ring Rd,"(24.7397288, 46.6463975)","(24.5539963, 46.5547852)",3.87,59.43,2,34.84,Blue
133,Yalamlam,"(24.7968728, 46.8017535)","(24.7544746, 46.7894252)",0.33,30.48,1,8.39,Blue
134,Yanbu,"(24.6492832, 46.5861072)","(24.5956169, 46.5018235)",2.78,39.43,1,14.61,Blue
136,أبي العتاهية,"(24.737833, 46.8325494)","(24.7014787, 46.7792927)",0.07,23.38,1,7.74,Blue
138,أبي عبيدة بن مسعود,"(24.7435132, 46.8325494)","(24.7020341, 46.8010727)",0.42,25.31,1,7.18,Blue
144,أحمد الموفق,"(24.6309504, 46.7043448)","(24.5838406, 46.6958899)",0.35,43.89,0,7.88,Yellow
145,أحمد عبدالواحد,"(24.7132022, 46.7652314)","(24.7113442, 46.7638708)",0.89,35.85,0,6.15,Blue
150,أم الزهر,"(24.7438936, 46.6958899)","(24.6915966, 46.6678181)",2.09,38.05,0,9.45,Blue
157,ابن كعب,"(24.7553853, 46.7635685)","(24.7181537, 46.7590336)",0.17,33.30,0,6.38,Blue
162,الأسود بن هلال,"(24.76340690000002, 46.6271734)","(24.74446739999997, 46.582252)",0.43,43.87,0,8.13,Blue
164,الأشقر,"(24.9081998, 46.9537969)","(24.8813536, 46.9283108)",0.01,43.10,0,7.44,Blue
166,الأمير فيصل بن عبدالعزيز بن سعود,"(24.6151277, 46.7067607)","(24.6092966, 46.6898516)",2.41,30.83,0,6.52,Orange
167,الأوزاعي,"(24.7533144, 46.80894)","(24.7153136, 46.7716568)",1.04,36.30,0,6.93,Yellow
168,الإسكندراني,"(24.7129533, 46.7762684)","(24.6739252, 46.7448269)",1.05,31.31,0,7.83,Blue
171,الإمام أحمد بن حنبل,"(24.768106, 46.8907119)","(24.6997523, 46.7768732)",0.32,51.14,1,21.08,Blue
174,الامام الشافعي,"(24.7318305, 46.815598)","(24.6784302, 46.7817122)",0.35,34.64,1,11.29,Blue
176,الباطن,"(24.7631338, 46.8028881)","(24.642655, 46.7315306)",3.76,45.77,2,22.58,Blue
178,البستان,"(24.7031341, 46.66630929999999)","(24.6959039, 46.6135303)",0.96,44.99,0,9.31,Blue
180,البيت العتيق,"(24.8112938, 46.7445247)","(24.7994054, 46.7188421)",0.91,38.11,0,7.55,Yellow
181,التخصصي,"(24.7577072, 46.6898516)","(24.6509204, 46.6367462)",2.01,47.91,1,22.84,Blue
185,التنهاة,"(24.7570374, 46.5981595)","(24.7397288, 46.58851749999999)",0.14,44.84,0,9.12,Blue
189,الحجل,"(24.7887347, 46.6807956)","(24.7847265, 46.6727974)",1.36,40.98,0,6.49,Orange
190,الحدبه,"(24.6195884, 46.7282071)","(24.5895889, 46.7234866)",2.33,27.43,0,6.98,Blue
191,الحميمة,"(24.6196381, 46.7297178)","(24.5983228, 46.6952861)",1.58,24.02,1,8.46,Blue
192,الحنكة,"(24.7861326, 46.7233733)","(24.7270423, 46.6850215)",1.18,46.32,0,11.41,Blue
193,الحيازين,"(24.7685712, 46.7794439)","(24.6891896, 46.77233709999999)",0.79,36.65,1,13.53,Blue
194,الخزان,"(24.6410953, 46.7260923)","(24.6339923, 46.6880403)",0.74,28.54,1,7.64,Blue
195,الخزرج,"(24.7851293, 46.6850215)","(24.7573837, 46.6596712)",0.65,37.66,0,7.17,Blue
201,الربيع - اليرموك,"(24.8246022, 46.80901840000001)","(24.7913163, 46.7581815)",0.07,29.92,1,10.08,Blue
202,الرسان,"(24.7279212, 46.7947917)","(24.6946911, 46.7618374)",0.01,42.80,0,10.18,Blue
204,السعادات,"(24.7175308, 46.8558487)","(24.6776424, 46.8168152)",0.34,36.17,0,9.48,Blue
206,السفح,"(24.6130618, 46.720428)","(24.5733974, 46.6964938)",0.50,32.79,1,8.95,Blue
213,الشعيرة,"(24.7468638, 46.7478493)","(24.7443783, 46.7114419)",0.32,41.98,0,8.05,Blue
215,الشيخ جابر الأحمد الصباح,"(24.8400346, 46.83012739999999)","(24.7790607, 46.7865516)",1.60,43.25,1,13.08,Blue
216,الشيخ حسن بن حسين بن علي,"(24.8467573, 46.7865516)","(24.7617666, 46.7381783)",1.95,48.61,1,16.18,Blue
217,الشيخ عبدالله المخضوب,"(24.7995141, 46.7094787)","(24.7878151, 46.6897762)",0.26,39.99,0,7.32,Blue
221,الصناعية,"(24.6541091, 46.7619944)","(24.630205, 46.7308212)",1.67,28.50,0,6.50,Blue
222,الضحى,"(24.7706736, 46.7019289)","(24.7356204, 46.6637445)",0.35,35.06,0,8.62,Blue
225,الطريق الدائري الجنوبي الفرعي,"(24.641973, 46.8204406)","(24.5383879, 46.5933382)",6.17,37.70,2,30.18,Blue
226,العباس بن عبدالمطلب,"(24.7841274, 46.7266965)","(24.7663703, 46.6898516)",0.34,45.91,0,8.04,Blue
228,العريجاء,"(24.6361119, 46.6731787)","(24.6126837, 46.6396075)",0.09,32.40,0,6.35,Blue
232,العينة,"(24.6479744, 46.592133)","(24.640628, 46.5710461)",1.66,43.76,0,6.93,Blue
235,الفروثي,"(24.764204, 46.6916631)","(24.7187709, 46.6844178)",1.04,34.67,0,7.41,Yellow
237,الفضول,"(24.7876258, 46.6967957)","(24.7288274, 46.658766)",1.83,47.12,0,10.92,Blue
238,الفكر,"(24.6403854, 46.73696959999999)","(24.6042262, 46.6898516)",4.39,27.72,1,12.66,Orange
239,القادسية,"(24.8395969, 46.8501623)","(24.8001838, 46.7978952)",1.67,39.23,1,11.39,Yellow
240,القاضي,"(24.7454537, 46.7146132)","(24.7408013, 46.7047977)",1.52,38.63,0,7.52,Blue
241,القريات,"(24.8239822, 46.6850215)","(24.8042754, 46.6752873)",2.01,41.74,0,6.83,Blue
242,القضيباء,"(24.8140247, 46.7218629)","(24.7792262, 46.6819652)",0.52,49.36,0,10.64,Blue
248,المحرق,"(24.706941, 46.6301119)","(24.7000669, 46.6255891)",0.49,43.99,0,5.98,Blue
253,المضيق,"(24.6975965, 46.7850392)","(24.6385203, 46.7118949)",3.17,29.00,2,13.68,Blue
254,المعيزيلة,"(24.8186427, 46.8597823)","(24.7649743, 46.8156829)",1.26,46.07,1,15.93,Blue
255,الملاح,"(24.6533723, 46.7454314)","(24.6162155, 46.7067607)",4.86,32.97,1,12.67,Yellow
257,الملك سلمان الفرعي,"(24.8558203, 46.6801919)","(24.8423717, 46.6530339)",0.51,56.54,0,7.00,Blue
258,الملك عبدالله,"(24.7598942, 46.7618374)","(24.7040611, 46.7211557)",0.80,44.11,1,12.81,Blue
260,المهندس مساعد العنقري,"(24.7263022, 46.6877384)","(24.7055021, 46.6753627)",1.08,39.65,1,10.85,Blue
265,الواحة,"(24.7519361, 46.7258057)","(24.7213988, 46.68524009999999)",1.22,41.55,0,8.59,Blue
266,الوصلة,"(24.8035774, 46.76749909999999)","(24.7855121, 46.71215919999999)",0.85,34.81,0,9.13,Yellow
268,الوليد بن مسلم,"(24.76329790000003, 46.61907649999999)","(24.74361729999997, 46.5815554)",0.34,44.97,0,8.44,Blue
269,الياسمين,"(24.8430476, 46.6698339)","(24.8006436, 46.6142181)",1.23,36.36,1,9.94,Blue
282,جبل عسيب,"(24.8325676, 46.744978)","(24.7791095, 46.6975506)",0.89,48.23,0,12.66,Blue
284,جديدة,"(24.6217074, 46.7164256)","(24.5872201, 46.6928707)",0.89,31.39,0,6.55,Yellow
288,جهام,"(24.808157, 46.7678014)","(24.7739725, 46.7179359)",0.72,36.44,0,8.73,Yellow
289,جويرية بنت الحارث,"(24.7511046, 46.6524305)","(24.7318878, 46.64157160000001)",1.67,46.45,0,7.10,Blue
292,حلبان,"(24.8037367, 46.782922)","(24.7736595, 46.73727179999999)",0.85,32.03,0,8.17,Yellow
293,حليمة السعدية,"(24.6184466, 46.7260923)","(24.6005061, 46.7164256)",3.01,23.41,1,6.22,Orange
294,حمد الخطيب,"(24.6846253, 46.7094787)","(24.6439315, 46.6995133)",1.90,27.43,0,6.63,Blue
296,خارجة بن حذافة,"(24.702937, 46.7442224)","(24.6982062, 46.7049487)",2.78,33.81,0,6.86,Red
297,خالد ابن الوليد,"(24.8177153, 46.7889715)","(24.7236044, 46.7285093)",2.39,44.15,2,22.94,Yellow
300,داود بن الهيثم,"(24.7946905, 46.8373937)","(24.7606591, 46.8107557)",0.77,43.13,0,10.41,Blue
303,راجية,"(24.8218292, 46.77324429999999)","(24.8027754, 46.7623591)",0.55,36.41,0,8.89,Blue
307,زهير بن المسيب,"(24.7519855, 46.7986522)","(24.6798075, 46.7647779)",2.29,40.20,1,12.10,Yellow
308,زهير بن حرب,"(24.6253448, 46.7212587)","(24.6057798, 46.6880403)",1.75,23.77,1,8.30,Blue
310,سامطة,"(24.7545783, 46.83622039999999)","(24.7340721, 46.802283)",0.26,53.40,0,9.80,Blue
314,سومطرة,"(24.7753276, 46.6602746)","(24.75078, 46.6165447)",0.67,49.34,0,7.13,Blue
315,شارع أبو ذر الغفاري,"(24.6876224, 46.7762684)","(24.6809226, 46.7572197)",0.31,36.80,0,7.39,Blue
321,شارع ابن شداد,"(24.6661731, 46.7312285)","(24.6540629, 46.6768718)",1.87,34.90,0,7.70,Blue
322,شارع الأمير تركي بن عبدالعزيز الثاني,"(24.7596584, 46.6644988)","(24.748831, 46.6409684)",0.18,46.71,0,6.87,Blue
323,شارع الأمير سلطان بن سلمان بن عبدالعزيز,"(24.7275999, 46.6813993)","(24.7154815, 46.6590677)",1.04,32.25,0,5.74,Blue
326,شارع الثلاثين,"(24.7059093, 46.7164256)","(24.6790947, 46.6657058)",2.11,39.05,0,9.01,Blue
327,شارع الحلوة,"(24.7981818, 46.6708358)","(24.7858495, 46.6222727)",0.23,32.23,0,7.58,Blue
328,شارع الزبير بن العوام,"(24.726966, 46.8399674)","(24.6854408, 46.7762684)",1.34,41.56,1,14.21,Yellow
330,شارع الفضل التميمي,"(24.759075, 46.6470008)","(24.7555028, 46.6448894)",2.16,36.69,0,7.43,Blue
331,شارع المدينة المنورة,"(24.6637135, 46.7962319)","(24.5627045, 46.574058)",5.20,52.00,2,34.21,Blue
332,شارع النايفية,"(24.7456243, 46.820138)","(24.7253957, 46.7752099)",0.11,37.28,0,6.48,Blue
338,شارع شرورة,"(24.805822, 46.7659873)","(24.7634044, 46.7405959)",0.04,31.84,0,8.14,Blue
339,شارع طريق الامام محمد بن سعود,"(24.7895371, 46.7526854)","(24.7271816, 46.6270967)",1.84,51.61,1,15.63,Blue
342,شارع على بن أبي طالب,"(24.6805135, 46.7671967)","(24.6134842, 46.7405959)",1.39,45.48,1,16.52,Blue
343,شارع عمر بن عبدالعزيز,"(24.7014787, 46.782922)","(24.6768552, 46.7260923)",0.01,31.41,0,8.10,Blue
344,شارع عنيزة,"(24.7108149, 46.7938116)","(24.6834606, 46.7720347)",0.11,32.18,0,7.11,Blue
346,شارع مؤتة,"(24.7362175, 46.6617832)","(24.6969381, 46.6569558)",0.21,38.13,0,6.23,Blue
349,شارع وادي حنيفة,"(24.7033408, 46.6807956)","(24.5998153, 46.60298119999999)",2.54,47.36,2,24.02,Yellow
352,صلاح الدين الأيوبي,"(24.7093659, 46.7774781)","(24.6525599, 46.7164256)",1.05,33.74,1,13.93,Yellow
355,طريق أبي بكر الصديق,"(24.9673426, 46.7285093)","(24.6981028, 46.58851749999999)",1.02,63.46,2,50.70,Blue
356,طريق الأمير سطام بن عبدالعزيز,"(24.6587247, 46.6801919)","(24.6158359, 46.6657058)",0.50,27.99,1,8.20,Blue
357,طريق الأمير سعد بن عبدالرحمن الأول,"(24.727772, 46.870105)","(24.6782849, 46.7768732)",0.71,57.76,1,21.97,Blue
360,طريق الامام سعود بن فيصل,"(24.8155263, 46.660878)","(24.773476, 46.5716484)",1.35,52.46,1,18.31,Blue
361,طريق الامير مساعد بن جلوي,"(24.7113313, 46.7188421)","(24.6422095, 46.6946822)",2.47,39.71,1,11.49,Blue
362,طريق الجنادرية,"(24.9690502, 46.8640458)","(24.7798871, 46.7859467)",0.05,53.21,2,29.77,Blue
363,طريق الرياض - الرمحية,"(24.6236475, 46.6989848)","(24.5854023, 46.6870969)",0.36,38.40,0,7.42,Blue
365,طريق العروبة,"(24.7435802, 46.7526854)","(24.6890813, 46.6270967)",3.35,46.11,1,18.35,Blue
367,طريق الملك فهد - الفرعي,"(24.7620395, 46.6898516)","(24.6764758, 46.6463975)",2.24,53.76,1,16.94,Blue
368,طريق الملك فيصل,"(24.6721253, 46.7236754)","(24.6170533, 46.6946822)",3.79,29.86,1,9.52,Blue
370,طريق تركي الأول بن عبدالعزيز آل سعود,"(24.8474334, 46.670534)","(24.6630729, 46.5547852)",0.26,54.92,2,28.87,Blue
374,طريق طلحة بن عبيدالله,"(24.717821, 46.855564)","(24.6826348, 46.7962319)",0.42,31.88,1,9.29,Yellow
375,طريق عمر بن الخطاب,"(24.6698077, 46.7865516)","(24.6443417, 46.71400920000001)",2.65,27.26,1,9.94,Blue
376,طريق منية,"(24.7542336, 46.7067607)","(24.7256334, 46.6569558)",1.93,39.77,0,7.41,Blue
379,عالية,"(24.7499246, 46.71174389999999)","(24.6996238, 46.6886441)",2.07,33.40,1,9.44,Blue
382,عبداللطيف الخيمي,"(24.6668921, 46.7040428)","(24.6644876, 46.6998152)",2.11,34.25,0,6.06,Orange
383,عبداللطيف بن عبدالملك آل الشيخ,"(24.825001, 46.6198608)","(24.7973643, 46.6053922)",1.43,27.89,0,6.15,Orange
386,عسفات,"(24.7874632, 46.7276406)","(24.7805653, 46.701023)",0.19,42.15,0,9.66,Blue
387,عسيلة,"(24.6110297, 46.6349367)","(24.5715898, 46.58490219999999)",0.47,30.11,1,8.85,Blue
391,عمرو بن العاص,"(24.6484974, 46.7073647)","(24.6325151, 46.6750609)",0.30,32.62,0,6.82,Blue
393,فرسان,"(24.7600848, 46.6536372)","(24.6897433, 46.6240816)",1.39,54.22,1,18.23,Blue
395,قرى الدار,"(24.6398012, 46.6240816)","(24.5923203, 46.5969164)",1.02,35.73,1,12.07,Blue
399,مثيبة,"(24.6250247, 46.7413514)","(24.5782971, 46.7029858)",2.67,39.81,1,12.81,Blue
401,محمد أبي حمزة,"(24.7599287, 46.6735519)","(24.7577633, 46.669176)",2.01,45.57,0,6.74,Blue
403,مسلم بن عبدالرحمن,"(24.7557343, 46.7900302)","(24.7222054, 46.76931330000001)",0.04,34.02,0,6.37,Blue
404,مصباح المالكي,"(24.658617, 46.75510370000001)","(24.6255656, 46.7106868)",2.32,23.08,1,9.67,Yellow
410,ممر قرطبة,"(24.8377564, 46.7581815)","(24.7926627, 46.7135863)",0.95,48.04,0,12.07,Blue
414,موسى بن نصير,"(24.7091818, 46.6910592)","(24.6931774, 46.6584643)",0.04,27.13,0,6.83,Blue
419,وادي الجناح,"(24.7058738, 46.6215189)","(24.7044394, 46.6194086)",0.28,53.10,0,8.27,Blue
420,وادي الحياة,"(24.780071, 46.67989009999999)","(24.7552731, 46.65001720000001)",0.48,54.54,0,6.01,Blue
421,وادي الساهية,"(24.7797288, 46.6524305)","(24.7557062, 46.6234786)",0.47,41.67,0,6.14,Blue
422,وادي الطيري,"(24.7382791, 46.7109888)","(24.6863312, 46.6849461)",5.52,36.24,1,11.48,Red
423,وادي ترج,"(24.7863531, 46.6940784)","(24.7813167, 46.6843423)",0.93,41.19,0,8.33,Blue
425,وادي لبن,"(24.6405615, 46.6512239)","(24.5680149, 46.4489184)",0.59,46.14,2,26.34,Blue
426,وادي هجر,"(24.8181963, 46.6186549)","(24.8093034, 46.6005703)",0.99,31.20,0,6.85,Blue
427,وعلة,"(24.6715975, 46.7441469)","(24.6187426, 46.6930971)",3.36,29.18,1,11.07,Blue
428,يوسف الأنفاسي,"(24.6555349, 46.7097808)","(24.6033697, 46.6638953)",0.04,32.60,1,10.97,Blue

In [ ]:
# # List of row indices to delete
# rows_to_delete = [ 46, 51, 52, 54, 62, 65, 72, 104, 107, 114, 117, 157, 170, 205, 216, 219, 224, 276, 291, 322]

# # Drop the rows with the specified indices
# df = df.drop(index=rows_to_delete)

# # The original dataframe 'df' is now updated with the specified rows deleted

In [ ]:
# # Select the specific rows from the DataFrame df
# rows_to_save = [0, 46, 51, 52, 54, 62, 65, 72, 104, 107, 114, 117, 157, 170, 205, 216, 219, 224, 276, 291, 322]

# # Get the rows from the DataFrame
# selected_rows = df.loc[rows_to_save]

# # Display the selected rows
# selected_rows

In [ ]:
# # List of row indices to delete
# rows_to_delete = [0,65, 72,276, 291]

# # Get a list of valid indices in the DataFrame
# valid_indices = df.index

# # Filter the list of rows to delete to only include valid indices
# rows_to_delete = [row for row in rows_to_delete if row in valid_indices]

# # Drop the rows with the specified indices
# df = df.drop(index=rows_to_delete)

# # The original dataframe 'df' is now updated with the specified rows deleted

In [ ]:
df.shape

(192, 8)

In [ ]:
df = df.reset_index(drop=True)

In [ ]:
df.loc[df['distance_km'] == df['distance_km'].max()]

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
91,King Abdul Aziz Road,"(24.9996923, 46.7285093)","(24.6422095, 46.5499681)",1.77,60.83,2,57.52,Blue

In [ ]:
df.loc[df['distance_km'] == df['distance_km'].min()]

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
140,شارع الأمير سلطان بن سلمان بن عبدالعزيز,"(24.7275999, 46.6813993)","(24.7154815, 46.6590677)",1.04,32.25,0,5.74,Blue

In [ ]:
df

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
0,3rd Roundabout,"(24.6652373, 46.7968369)","(24.6631823, 46.7870053)",0.02,48.38,0,6.09,Blue
1,Abdulaziz Al Fereh,"(24.6746147, 46.73819719999999)","(24.586689, 46.6373493)",0.96,33.72,2,19.60,Blue
2,Abi Hasain Al Hanbali,"(24.8022123, 46.6638953)","(24.7837499, 46.6243831)",0.10,34.61,0,8.82,Blue
3,Abu Thabit,"(24.7534692, 46.8495065)","(24.7095964, 46.815598)",0.09,47.17,1,14.76,Blue
4,Airport Road,"(24.9974697, 46.7381783)","(24.7791458, 46.6512239)",0.73,51.72,2,36.60,Blue
5,Al Abbas Al Rashidi St.,"(24.6923431, 46.8495065)","(24.5915754, 46.7865516)",2.29,45.69,2,22.51,Blue
6,Al Ammar,"(24.7286847, 46.6826067)","(24.6936181, 46.6457942)",0.26,27.17,0,6.96,Blue
7,Al Anbari,"(24.7330062, 46.7599405)","(24.6821831, 46.74875600000001)",0.20,36.43,0,8.36,Blue
8,Al Ataya,"(24.7536362, 46.7623591)","(24.7333674, 46.7088747)",0.33,38.30,0,7.23,Blue
9,Al Basham St.,"(24.7493703, 46.8243757)","(24.6834516, 46.7679526)",1.67,43.85,1,13.81,Yellow
10,Al Falah,"(24.8091397, 46.7223406)","(24.785114, 46.6960814)",0.38,39.93,0,9.20,Blue
11,Al Farish,"(24.7891692, 46.7170297)","(24.7480719, 46.6687234)",0.75,48.15,0,11.34,Blue
12,Al Farzdaq Street,"(24.6870478, 46.7430136)","(24.6048722, 46.7188421)",0.75,32.11,2,16.02,Blue
13,Al Ghareeb,"(24.7235842, 46.7901815)","(24.6767355, 46.7497383)",0.24,37.55,1,10.71,Blue
14,Al Ghazaleh Path,"(24.6578442, 46.7031368)","(24.6255367, 46.6812483)",0.77,38.37,0,6.74,Blue
15,Al Hareth,"(24.8013768, 46.7484915)","(24.742101, 46.7052507)",2.19,35.90,1,11.40,Blue
16,Al Jabour,"(24.6440511, 46.7655337)","(24.6101493, 46.7170297)",2.12,28.89,1,10.52,Blue
17,Al Muhareb,"(24.6431497, 46.7285093)","(24.5460354, 46.6476041)",4.37,42.34,2,20.86,Blue
18,Al Nahdha road,"(24.7084691, 46.7865516)","(24.6251442, 46.7430136)",1.39,49.14,1,18.72,Blue
19,Al Naqeel,"(24.7610666, 46.65562389999999)","(24.7238296, 46.5904416)",0.58,49.73,1,15.05,Blue
20,Al Olaya,"(24.7165527, 46.7035117)","(24.6682398, 46.66354519999999)",1.91,40.26,1,12.85,Blue
21,Al Rabeah Aljarmi,"(24.7391318, 46.7587313)","(24.6933374, 46.7555571)",0.40,39.11,0,9.08,Blue
22,Al Raed,"(24.7205795, 46.6541829)","(24.694263, 46.62321)",0.90,36.45,0,8.23,Blue
23,Al Rawdh,"(24.7532343, 46.7870871)","(24.7145113, 46.7488715)",0.53,39.76,0,9.40,Yellow
24,Al Rumh,"(24.7587914, 46.6898516)","(24.7200682, 46.67294829999999)",0.30,34.37,0,7.88,Blue
25,Al Sanya al Baida,"(24.7310537, 46.84344979999999)","(24.6808089, 46.7578244)",0.67,36.20,1,14.23,Yellow
26,Al Shaba'Niah,"(24.8519613, 46.805914)","(24.7657102, 46.7212587)",1.93,51.08,1,18.83,Blue
27,Al Thoumamah Rd,"(24.9378398, 46.815598)","(24.7479639, 46.6319212)",1.30,56.96,2,34.07,Blue
28,Al Ward,"(24.6770813, 46.5903299)","(24.6277137, 46.54394749999999)",1.87,36.39,1,11.98,Blue
29,Al-Fajar,"(24.8180188, 46.6660075)","(24.8126, 46.6558999)",1.17,46.88,0,7.57,Yellow
30,Atia,"(24.7736461, 46.7222027)","(24.7524547, 46.6826067)",0.75,44.05,0,6.01,Yellow
31,Dammam Road,"(24.9568714, 47.0291162)","(24.7886798, 46.7188421)",0.67,71.85,2,47.04,Blue
32,Discovery Blvd,"(24.7659472, 46.6391588)","(24.7607916, 46.636143)",0.41,45.30,0,9.95,Blue
33,East Ring Road,"(24.7921447, 46.805914)","(24.6224894, 46.7188421)",4.97,46.10,2,35.51,Blue
34,FAHHAD MOHAMMAD AL JFIRAN STREET,"(24.68896, 46.76417319999999)","(24.6840036, 46.7132541)",1.14,30.06,1,8.91,Blue
35,Imam Malik Road,"(24.8506483, 46.7188421)","(24.7825477, 46.56863670000001)",2.42,52.24,1,22.28,Yellow
36,Jeddah Road,"(24.6942703, 46.64157160000001)","(24.5263166, 46.4387046)",2.34,75.92,2,52.83,Blue
37,Khurais Road,"(24.946473, 46.9999471)","(24.7106093, 46.7623591)",3.50,70.07,2,41.16,Blue
38,King Abdul Aziz Road,"(24.9996923, 46.7285093)","(24.6422095, 46.5499681)",1.77,60.83,2,57.52,Blue
39,King Abdulaziz,"(24.7427455, 46.7450497)","(24.6935528, 46.6929946)",2.52,36.14,1,11.75,Yellow
40,King Abdullah Road,"(24.801193, 46.8204406)","(24.6968763, 46.6222727)",4.19,57.52,1,25.50,Blue
41,King Salman Road,"(24.97692050000003, 46.7237318)","(24.79621499999998, 46.5574488)",0.95,68.24,2,42.18,Blue
42,King Saud,"(24.6933354, 46.7188421)","(24.638759, 46.6457942)",3.14,40.43,1,13.38,Blue
43,Laban Valley,"(24.6575726, 46.6508675)","(24.6016845, 46.563363)",2.98,51.00,1,21.29,Blue
44,Maan Bin Ows,"(24.6320336, 46.8010727)","(24.6273961, 46.7913915)",1.52,45.83,0,7.16,Blue
45,Makkah al-Mukarramah Road,"(24.7201491, 46.7671967)","(24.6656897, 46.6367462)",3.89,48.51,1,16.70,Blue
46,Masafi,"(24.8249208, 46.7484538)","(24.7987016, 46.7084972)",0.05,39.30,0,7.17,Blue
47,Mohamed Ibn Hamd Ibn Faris,"(24.6679326, 46.7478493)","(24.6359973, 46.7285093)",2.46,26.47,0,6.54,Blue
48,Mohammed Ali Jinnah,"(24.8148754, 46.7986522)","(24.7545582, 46.6995133)",0.76,47.61,1,17.84,Blue
49,No.2,"(24.8184527, 46.6657058)","(24.8152541, 46.6584643)",0.76,48.81,0,6.64,Blue
50,No.509,"(24.9625832, 46.7285093)","(24.699414, 46.574058)",1.40,69.78,2,48.18,Blue
51,Northern Ring Road,"(24.9560346, 47.01452949999999)","(24.7258755, 46.5830947)",2.80,77.95,2,55.00,Blue
52,Olaya Road,"(24.8302126, 46.6995133)","(24.6639052, 46.612626)",2.69,60.91,2,38.20,Blue
53,Omar Al Hajeb,"(24.7854632, 46.8028881)","(24.760707, 46.7590336)",0.37,32.06,0,6.34,Blue
54,Othman Bin Affan Road,"(24.8540833, 46.7285093)","(24.7410088, 46.670534)",4.22,52.66,1,19.09,Blue
55,Qaha,"(24.8094773, 46.7508718)","(24.7984307, 46.712499)",0.56,45.99,0,7.06,Blue
56,Raghdan,"(24.6722289, 46.7345617)","(24.6388126, 46.7019289)",1.46,24.44,1,6.51,Blue
57,Sabta,"(24.76491, 46.6699305)","(24.7191642, 46.6578609)",1.80,41.48,0,7.75,Blue
58,Saeed Bin Amer,"(24.7272521, 46.7727151)","(24.6793498, 46.7581267)",0.12,37.10,0,8.82,Blue
59,Shab uldin Al taj,"(24.78133100000002, 46.6595165)","(24.73717459999997, 46.5755256)",0.82,55.24,0,12.46,Blue
60,Soukh Thi Al Mjaz,"(24.6817475, 46.7546277)","(24.6475414, 46.716127)",0.74,29.46,1,8.52,Blue
61,Tariq Bin Shabab,"(24.6226251, 46.7671967)","(24.5785679, 46.7430136)",1.31,39.14,0,10.27,Blue
62,Western Ring Rd,"(24.7397288, 46.6463975)","(24.5539963, 46.5547852)",3.87,59.43,2,34.84,Blue
63,Yalamlam,"(24.7968728, 46.8017535)","(24.7544746, 46.7894252)",0.33,30.48,1,8.39,Blue
64,Yanbu,"(24.6492832, 46.5861072)","(24.5956169, 46.5018235)",2.78,39.43,1,14.61,Blue
65,أبي العتاهية,"(24.737833, 46.8325494)","(24.7014787, 46.7792927)",0.07,23.38,1,7.74,Blue
66,أبي عبيدة بن مسعود,"(24.7435132, 46.8325494)","(24.7020341, 46.8010727)",0.42,25.31,1,7.18,Blue
67,أحمد الموفق,"(24.6309504, 46.7043448)","(24.5838406, 46.6958899)",0.35,43.89,0,7.88,Yellow
68,أحمد عبدالواحد,"(24.7132022, 46.7652314)","(24.7113442, 46.7638708)",0.89,35.85,0,6.15,Blue
69,أم الزهر,"(24.7438936, 46.6958899)","(24.6915966, 46.6678181)",2.09,38.05,0,9.45,Blue
70,ابن كعب,"(24.7553853, 46.7635685)","(24.7181537, 46.7590336)",0.17,33.30,0,6.38,Blue
71,الأسود بن هلال,"(24.76340690000002, 46.6271734)","(24.74446739999997, 46.582252)",0.43,43.87,0,8.13,Blue
72,الأشقر,"(24.9081998, 46.9537969)","(24.8813536, 46.9283108)",0.01,43.10,0,7.44,Blue
73,الأمير فيصل بن عبدالعزيز بن سعود,"(24.6151277, 46.7067607)","(24.6092966, 46.6898516)",2.41,30.83,0,6.52,Orange
74,الأوزاعي,"(24.7533144, 46.80894)","(24.7153136, 46.7716568)",1.04,36.30,0,6.93,Yellow
75,الإسكندراني,"(24.7129533, 46.7762684)","(24.6739252, 46.7448269)",1.05,31.31,0,7.83,Blue
76,الإمام أحمد بن حنبل,"(24.768106, 46.8907119)","(24.6997523, 46.7768732)",0.32,51.14,1,21.08,Blue
77,الامام الشافعي,"(24.7318305, 46.815598)","(24.6784302, 46.7817122)",0.35,34.64,1,11.29,Blue
78,الباطن,"(24.7631338, 46.8028881)","(24.642655, 46.7315306)",3.76,45.77,2,22.58,Blue
79,البستان,"(24.7031341, 46.66630929999999)","(24.6959039, 46.6135303)",0.96,44.99,0,9.31,Blue
80,البيت العتيق,"(24.8112938, 46.7445247)","(24.7994054, 46.7188421)",0.91,38.11,0,7.55,Yellow
81,التخصصي,"(24.7577072, 46.6898516)","(24.6509204, 46.6367462)",2.01,47.91,1,22.84,Blue
82,التنهاة,"(24.7570374, 46.5981595)","(24.7397288, 46.58851749999999)",0.14,44.84,0,9.12,Blue
83,الحجل,"(24.7887347, 46.6807956)","(24.7847265, 46.6727974)",1.36,40.98,0,6.49,Orange
84,الحدبه,"(24.6195884, 46.7282071)","(24.5895889, 46.7234866)",2.33,27.43,0,6.98,Blue
85,الحميمة,"(24.6196381, 46.7297178)","(24.5983228, 46.6952861)",1.58,24.02,1,8.46,Blue
86,الحنكة,"(24.7861326, 46.7233733)","(24.7270423, 46.6850215)",1.18,46.32,0,11.41,Blue
87,الحيازين,"(24.7685712, 46.7794439)","(24.6891896, 46.77233709999999)",0.79,36.65,1,13.53,Blue
88,الخزان,"(24.6410953, 46.7260923)","(24.6339923, 46.6880403)",0.74,28.54,1,7.64,Blue
89,الخزرج,"(24.7851293, 46.6850215)","(24.7573837, 46.6596712)",0.65,37.66,0,7.17,Blue
90,الربيع - اليرموك,"(24.8246022, 46.80901840000001)","(24.7913163, 46.7581815)",0.07,29.92,1,10.08,Blue
91,الرسان,"(24.7279212, 46.7947917)","(24.6946911, 46.7618374)",0.01,42.80,0,10.18,Blue
92,السعادات,"(24.7175308, 46.8558487)","(24.6776424, 46.8168152)",0.34,36.17,0,9.48,Blue
93,السفح,"(24.6130618, 46.720428)","(24.5733974, 46.6964938)",0.50,32.79,1,8.95,Blue
94,الشعيرة,"(24.7468638, 46.7478493)","(24.7443783, 46.7114419)",0.32,41.98,0,8.05,Blue
95,الشيخ جابر الأحمد الصباح,"(24.8400346, 46.83012739999999)","(24.7790607, 46.7865516)",1.60,43.25,1,13.08,Blue
96,الشيخ حسن بن حسين بن علي,"(24.8467573, 46.7865516)","(24.7617666, 46.7381783)",1.95,48.61,1,16.18,Blue
97,الشيخ عبدالله المخضوب,"(24.7995141, 46.7094787)","(24.7878151, 46.6897762)",0.26,39.99,0,7.32,Blue
98,الصناعية,"(24.6541091, 46.7619944)","(24.630205, 46.7308212)",1.67,28.50,0,6.50,Blue
99,الضحى,"(24.7706736, 46.7019289)","(24.7356204, 46.6637445)",0.35,35.06,0,8.62,Blue
100,الطريق الدائري الجنوبي الفرعي,"(24.641973, 46.8204406)","(24.5383879, 46.5933382)",6.17,37.70,2,30.18,Blue
101,العباس بن عبدالمطلب,"(24.7841274, 46.7266965)","(24.7663703, 46.6898516)",0.34,45.91,0,8.04,Blue
102,العريجاء,"(24.6361119, 46.6731787)","(24.6126837, 46.6396075)",0.09,32.40,0,6.35,Blue
103,العينة,"(24.6479744, 46.592133)","(24.640628, 46.5710461)",1.66,43.76,0,6.93,Blue
104,الفروثي,"(24.764204, 46.6916631)","(24.7187709, 46.6844178)",1.04,34.67,0,7.41,Yellow
105,الفضول,"(24.7876258, 46.6967957)","(24.7288274, 46.658766)",1.83,47.12,0,10.92,Blue
106,الفكر,"(24.6403854, 46.73696959999999)","(24.6042262, 46.6898516)",4.39,27.72,1,12.66,Orange
107,القادسية,"(24.8395969, 46.8501623)","(24.8001838, 46.7978952)",1.67,39.23,1,11.39,Yellow
108,القاضي,"(24.7454537, 46.7146132)","(24.7408013, 46.7047977)",1.52,38.63,0,7.52,Blue
109,القريات,"(24.8239822, 46.6850215)","(24.8042754, 46.6752873)",2.01,41.74,0,6.83,Blue
110,القضيباء,"(24.8140247, 46.7218629)","(24.7792262, 46.6819652)",0.52,49.36,0,10.64,Blue
111,المحرق,"(24.706941, 46.6301119)","(24.7000669, 46.6255891)",0.49,43.99,0,5.98,Blue
112,المضيق,"(24.6975965, 46.7850392)","(24.6385203, 46.7118949)",3.17,29.00,2,13.68,Blue
113,المعيزيلة,"(24.8186427, 46.8597823)","(24.7649743, 46.8156829)",1.26,46.07,1,15.93,Blue
114,الملاح,"(24.6533723, 46.7454314)","(24.6162155, 46.7067607)",4.86,32.97,1,12.67,Yellow
115,الملك سلمان الفرعي,"(24.8558203, 46.6801919)","(24.8423717, 46.6530339)",0.51,56.54,0,7.00,Blue
116,الملك عبدالله,"(24.7598942, 46.7618374)","(24.7040611, 46.7211557)",0.80,44.11,1,12.81,Blue
117,المهندس مساعد العنقري,"(24.7263022, 46.6877384)","(24.7055021, 46.6753627)",1.08,39.65,1,10.85,Blue
118,الواحة,"(24.7519361, 46.7258057)","(24.7213988, 46.68524009999999)",1.22,41.55,0,8.59,Blue
119,الوصلة,"(24.8035774, 46.76749909999999)","(24.7855121, 46.71215919999999)",0.85,34.81,0,9.13,Yellow
120,الوليد بن مسلم,"(24.76329790000003, 46.61907649999999)","(24.74361729999997, 46.5815554)",0.34,44.97,0,8.44,Blue
121,الياسمين,"(24.8430476, 46.6698339)","(24.8006436, 46.6142181)",1.23,36.36,1,9.94,Blue
122,جبل عسيب,"(24.8325676, 46.744978)","(24.7791095, 46.6975506)",0.89,48.23,0,12.66,Blue
123,جديدة,"(24.6217074, 46.7164256)","(24.5872201, 46.6928707)",0.89,31.39,0,6.55,Yellow
124,جهام,"(24.808157, 46.7678014)","(24.7739725, 46.7179359)",0.72,36.44,0,8.73,Yellow
125,جويرية بنت الحارث,"(24.7511046, 46.6524305)","(24.7318878, 46.64157160000001)",1.67,46.45,0,7.10,Blue
126,حلبان,"(24.8037367, 46.782922)","(24.7736595, 46.73727179999999)",0.85,32.03,0,8.17,Yellow
127,حليمة السعدية,"(24.6184466, 46.7260923)","(24.6005061, 46.7164256)",3.01,23.41,1,6.22,Orange
128,حمد الخطيب,"(24.6846253, 46.7094787)","(24.6439315, 46.6995133)",1.90,27.43,0,6.63,Blue
129,خارجة بن حذافة,"(24.702937, 46.7442224)","(24.6982062, 46.7049487)",2.78,33.81,0,6.86,Red
130,خالد ابن الوليد,"(24.8177153, 46.7889715)","(24.7236044, 46.7285093)",2.39,44.15,2,22.94,Yellow
131,داود بن الهيثم,"(24.7946905, 46.8373937)","(24.7606591, 46.8107557)",0.77,43.13,0,10.41,Blue
132,راجية,"(24.8218292, 46.77324429999999)","(24.8027754, 46.7623591)",0.55,36.41,0,8.89,Blue
133,زهير بن المسيب,"(24.7519855, 46.7986522)","(24.6798075, 46.7647779)",2.29,40.20,1,12.10,Yellow
134,زهير بن حرب,"(24.6253448, 46.7212587)","(24.6057798, 46.6880403)",1.75,23.77,1,8.30,Blue
135,سامطة,"(24.7545783, 46.83622039999999)","(24.7340721, 46.802283)",0.26,53.40,0,9.80,Blue
136,سومطرة,"(24.7753276, 46.6602746)","(24.75078, 46.6165447)",0.67,49.34,0,7.13,Blue
137,شارع أبو ذر الغفاري,"(24.6876224, 46.7762684)","(24.6809226, 46.7572197)",0.31,36.80,0,7.39,Blue
138,شارع ابن شداد,"(24.6661731, 46.7312285)","(24.6540629, 46.6768718)",1.87,34.90,0,7.70,Blue
139,شارع الأمير تركي بن عبدالعزيز الثاني,"(24.7596584, 46.6644988)","(24.748831, 46.6409684)",0.18,46.71,0,6.87,Blue
140,شارع الأمير سلطان بن سلمان بن عبدالعزيز,"(24.7275999, 46.6813993)","(24.7154815, 46.6590677)",1.04,32.25,0,5.74,Blue
141,شارع الثلاثين,"(24.7059093, 46.7164256)","(24.6790947, 46.6657058)",2.11,39.05,0,9.01,Blue
142,شارع الحلوة,"(24.7981818, 46.6708358)","(24.7858495, 46.6222727)",0.23,32.23,0,7.58,Blue
143,شارع الزبير بن العوام,"(24.726966, 46.8399674)","(24.6854408, 46.7762684)",1.34,41.56,1,14.21,Yellow
144,شارع الفضل التميمي,"(24.759075, 46.6470008)","(24.7555028, 46.6448894)",2.16,36.69,0,7.43,Blue
145,شارع المدينة المنورة,"(24.6637135, 46.7962319)","(24.5627045, 46.574058)",5.20,52.00,2,34.21,Blue
146,شارع النايفية,"(24.7456243, 46.820138)","(24.7253957, 46.7752099)",0.11,37.28,0,6.48,Blue
147,شارع شرورة,"(24.805822, 46.7659873)","(24.7634044, 46.7405959)",0.04,31.84,0,8.14,Blue
148,شارع طريق الامام محمد بن سعود,"(24.7895371, 46.7526854)","(24.7271816, 46.6270967)",1.84,51.61,1,15.63,Blue
149,شارع على بن أبي طالب,"(24.6805135, 46.7671967)","(24.6134842, 46.7405959)",1.39,45.48,1,16.52,Blue
150,شارع عمر بن عبدالعزيز,"(24.7014787, 46.782922)","(24.6768552, 46.7260923)",0.01,31.41,0,8.10,Blue
151,شارع عنيزة,"(24.7108149, 46.7938116)","(24.6834606, 46.7720347)",0.11,32.18,0,7.11,Blue
152,شارع مؤتة,"(24.7362175, 46.6617832)","(24.6969381, 46.6569558)",0.21,38.13,0,6.23,Blue
153,شارع وادي حنيفة,"(24.7033408, 46.6807956)","(24.5998153, 46.60298119999999)",2.54,47.36,2,24.02,Yellow
154,صلاح الدين الأيوبي,"(24.7093659, 46.7774781)","(24.6525599, 46.7164256)",1.05,33.74,1,13.93,Yellow
155,طريق أبي بكر الصديق,"(24.9673426, 46.7285093)","(24.6981028, 46.58851749999999)",1.02,63.46,2,50.70,Blue
156,طريق الأمير سطام بن عبدالعزيز,"(24.6587247, 46.6801919)","(24.6158359, 46.6657058)",0.50,27.99,1,8.20,Blue
157,طريق الأمير سعد بن عبدالرحمن الأول,"(24.727772, 46.870105)","(24.6782849, 46.7768732)",0.71,57.76,1,21.97,Blue
158,طريق الامام سعود بن فيصل,"(24.8155263, 46.660878)","(24.773476, 46.5716484)",1.35,52.46,1,18.31,Blue
159,طريق الامير مساعد بن جلوي,"(24.7113313, 46.7188421)","(24.6422095, 46.6946822)",2.47,39.71,1,11.49,Blue
160,طريق الجنادرية,"(24.9690502, 46.8640458)","(24.7798871, 46.7859467)",0.05,53.21,2,29.77,Blue
161,طريق الرياض - الرمحية,"(24.6236475, 46.6989848)","(24.5854023, 46.6870969)",0.36,38.40,0,7.42,Blue
162,طريق العروبة,"(24.7435802, 46.7526854)","(24.6890813, 46.6270967)",3.35,46.11,1,18.35,Blue
163,طريق الملك فهد - الفرعي,"(24.7620395, 46.6898516)","(24.6764758, 46.6463975)",2.24,53.76,1,16.94,Blue
164,طريق الملك فيصل,"(24.6721253, 46.7236754)","(24.6170533, 46.6946822)",3.79,29.86,1,9.52,Blue
165,طريق تركي الأول بن عبدالعزيز آل سعود,"(24.8474334, 46.670534)","(24.6630729, 46.5547852)",0.26,54.92,2,28.87,Blue
166,طريق طلحة بن عبيدالله,"(24.717821, 46.855564)","(24.6826348, 46.7962319)",0.42,31.88,1,9.29,Yellow
167,طريق عمر بن الخطاب,"(24.6698077, 46.7865516)","(24.6443417, 46.71400920000001)",2.65,27.26,1,9.94,Blue
168,طريق منية,"(24.7542336, 46.7067607)","(24.7256334, 46.6569558)",1.93,39.77,0,7.41,Blue
169,عالية,"(24.7499246, 46.71174389999999)","(24.6996238, 46.6886441)",2.07,33.40,1,9.44,Blue
170,عبداللطيف الخيمي,"(24.6668921, 46.7040428)","(24.6644876, 46.6998152)",2.11,34.25,0,6.06,Orange
171,عبداللطيف بن عبدالملك آل الشيخ,"(24.825001, 46.6198608)","(24.7973643, 46.6053922)",1.43,27.89,0,6.15,Orange
172,عسفات,"(24.7874632, 46.7276406)","(24.7805653, 46.701023)",0.19,42.15,0,9.66,Blue
173,عسيلة,"(24.6110297, 46.6349367)","(24.5715898, 46.58490219999999)",0.47,30.11,1,8.85,Blue
174,عمرو بن العاص,"(24.6484974, 46.7073647)","(24.6325151, 46.6750609)",0.30,32.62,0,6.82,Blue
175,فرسان,"(24.7600848, 46.6536372)","(24.6897433, 46.6240816)",1.39,54.22,1,18.23,Blue
176,قرى الدار,"(24.6398012, 46.6240816)","(24.5923203, 46.5969164)",1.02,35.73,1,12.07,Blue
177,مثيبة,"(24.6250247, 46.7413514)","(24.5782971, 46.7029858)",2.67,39.81,1,12.81,Blue
178,محمد أبي حمزة,"(24.7599287, 46.6735519)","(24.7577633, 46.669176)",2.01,45.57,0,6.74,Blue
179,مسلم بن عبدالرحمن,"(24.7557343, 46.7900302)","(24.7222054, 46.76931330000001)",0.04,34.02,0,6.37,Blue
180,مصباح المالكي,"(24.658617, 46.75510370000001)","(24.6255656, 46.7106868)",2.32,23.08,1,9.67,Yellow
181,ممر قرطبة,"(24.8377564, 46.7581815)","(24.7926627, 46.7135863)",0.95,48.04,0,12.07,Blue
182,موسى بن نصير,"(24.7091818, 46.6910592)","(24.6931774, 46.6584643)",0.04,27.13,0,6.83,Blue
183,وادي الجناح,"(24.7058738, 46.6215189)","(24.7044394, 46.6194086)",0.28,53.10,0,8.27,Blue
184,وادي الحياة,"(24.780071, 46.67989009999999)","(24.7552731, 46.65001720000001)",0.48,54.54,0,6.01,Blue
185,وادي الساهية,"(24.7797288, 46.6524305)","(24.7557062, 46.6234786)",0.47,41.67,0,6.14,Blue
186,وادي الطيري,"(24.7382791, 46.7109888)","(24.6863312, 46.6849461)",5.52,36.24,1,11.48,Red
187,وادي ترج,"(24.7863531, 46.6940784)","(24.7813167, 46.6843423)",0.93,41.19,0,8.33,Blue
188,وادي لبن,"(24.6405615, 46.6512239)","(24.5680149, 46.4489184)",0.59,46.14,2,26.34,Blue
189,وادي هجر,"(24.8181963, 46.6186549)","(24.8093034, 46.6005703)",0.99,31.20,0,6.85,Blue
190,وعلة,"(24.6715975, 46.7441469)","(24.6187426, 46.6930971)",3.36,29.18,1,11.07,Blue
191,يوسف الأنفاسي,"(24.6555349, 46.7097808)","(24.6033697, 46.6638953)",0.04,32.60,1,10.97,Blue

In [ ]:
# X = df.loc[:, ['duration_in_traffic_min', 'distance_km']]

In [ ]:
# import matplotlib.pyplot as plt
# plt.figure(figsize=(10,5))
# plt.scatter(x= X['duration_in_traffic_min'], y=X['distance_km'])
# plt.xlabel('duration_in_traffic_min')
# plt.ylabel('distance_km');

In [ ]:
#X

In [ ]:
# df['distance_km'].max()

57.52

In [ ]:
# pd.set_option('display.max_rows', None)
# df

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
0,'Al Sabe,"(24.598009, 46.5957488)","(24.5954907, 46.5925096)",1.34,49.99,0,11.73,Blue
1,110 ممر,"(24.594892, 46.6403652)","(24.571468, 46.5812872)",1.18,34.51,0,8.40,Yellow
2,3rd Roundabout,"(24.6652373, 46.7968369)","(24.6631823, 46.7870053)",0.02,48.38,0,6.09,Blue
5,Abdulaziz Al Fereh,"(24.6746147, 46.73819719999999)","(24.586689, 46.6373493)",0.96,33.72,2,19.60,Blue
7,Abi Hasain Al Hanbali,"(24.8022123, 46.6638953)","(24.7837499, 46.6243831)",0.10,34.61,0,8.82,Blue
10,Abu Thabit,"(24.7534692, 46.8495065)","(24.7095964, 46.815598)",0.09,47.17,1,14.76,Blue
11,Afif,"(23.9556658, 42.9571364)","(23.8511982, 42.8685665)",0.83,49.58,1,17.44,Blue
12,Airport Road,"(24.9974697, 46.7381783)","(24.7791458, 46.6512239)",0.73,51.72,2,36.60,Blue
14,Al Abbas Al Rashidi St.,"(24.6923431, 46.8495065)","(24.5915754, 46.7865516)",2.29,45.69,2,22.51,Blue
16,Al Ammar,"(24.7286847, 46.6826067)","(24.6936181, 46.6457942)",0.26,27.17,0,6.96,Blue
17,Al Anbari,"(24.7330062, 46.7599405)","(24.6821831, 46.74875600000001)",0.20,36.43,0,8.36,Blue
18,Al Ataya,"(24.7536362, 46.7623591)","(24.7333674, 46.7088747)",0.33,38.30,0,7.23,Blue
20,Al Basham St.,"(24.7493703, 46.8243757)","(24.6834516, 46.7679526)",1.67,43.85,1,13.81,Yellow
21,Al Difa,"(24.5983788, 46.8560037)","(24.5735721, 46.8088237)",1.19,45.51,1,19.72,Blue
22,Al Falah,"(24.8091397, 46.7223406)","(24.785114, 46.6960814)",0.38,39.93,0,9.20,Blue
23,Al Farish,"(24.7891692, 46.7170297)","(24.7480719, 46.6687234)",0.75,48.15,0,11.34,Blue
24,Al Farzdaq Street,"(24.6870478, 46.7430136)","(24.6048722, 46.7188421)",0.75,32.11,2,16.02,Blue
26,Al Ghareeb,"(24.7235842, 46.7901815)","(24.6767355, 46.7497383)",0.24,37.55,1,10.71,Blue
27,Al Ghazaleh Path,"(24.6578442, 46.7031368)","(24.6255367, 46.6812483)",0.77,38.37,0,6.74,Blue
30,Al Hareth,"(24.8013768, 46.7484915)","(24.742101, 46.7052507)",2.19,35.90,1,11.40,Blue
32,Al Imam S'Aud Bin Abdulaziz Bin Mohammed,"(24.6060597, 46.8495065)","(24.5533825, 46.7744539)",1.43,42.39,2,22.27,Blue
33,Al Jabour,"(24.6440511, 46.7655337)","(24.6101493, 46.7170297)",2.12,28.89,1,10.52,Blue
42,Al Muhareb,"(24.6431497, 46.7285093)","(24.5460354, 46.6476041)",4.37,42.34,2,20.86,Blue
44,Al Nahdha road,"(24.7084691, 46.7865516)","(24.6251442, 46.7430136)",1.39,49.14,1,18.72,Blue
45,Al Naqeel,"(24.7610666, 46.65562389999999)","(24.7238296, 46.5904416)",0.58,49.73,1,15.05,Blue
46,Al Nasser,"(24.6030097, 46.7889715)","(24.5762585, 46.737574)",1.84,40.09,1,10.92,Yellow
47,Al Olaya,"(24.7165527, 46.7035117)","(24.6682398, 46.66354519999999)",1.91,40.26,1,12.85,Blue
48,Al Rabeah Aljarmi,"(24.7391318, 46.7587313)","(24.6933374, 46.7555571)",0.40,39.11,0,9.08,Blue
49,Al Raed,"(24.7205795, 46.6541829)","(24.694263, 46.62321)",0.90,36.45,0,8.23,Blue
52,Al Rawdh,"(24.7532343, 46.7870871)","(24.7145113, 46.7488715)",0.53,39.76,0,9.40,Yellow
54,Al Rumh,"(24.7587914, 46.6898516)","(24.7200682, 46.67294829999999)",0.30,34.37,0,7.88,Blue
56,Al Sanya al Baida,"(24.7310537, 46.84344979999999)","(24.6808089, 46.7578244)",0.67,36.20,1,14.23,Yellow
58,Al Shaba'Niah,"(24.8519613, 46.805914)","(24.7657102, 46.7212587)",1.93,51.08,1,18.83,Blue
61,Al Thoumamah Rd,"(24.9378398, 46.815598)","(24.7479639, 46.6319212)",1.30,56.96,2,34.07,Blue
63,Al Ward,"(24.6770813, 46.5903299)","(24.6277137, 46.54394749999999)",1.87,36.39,1,11.98,Blue
64,Al-Fajar,"(24.8180188, 46.6660075)","(24.8126, 46.6558999)",1.17,46.88,0,7.57,Yellow
69,Atia,"(24.7736461, 46.7222027)","(24.7524547, 46.6826067)",0.75,44.05,0,6.01,Yellow
72,Conference Blvd,"(24.7609007, 46.6422125)","(24.7582481, 46.6373493)",0.36,42.40,0,8.38,Blue
73,Dammam Road,"(24.9568714, 47.0291162)","(24.7886798, 46.7188421)",0.67,71.85,2,47.04,Blue
76,Discovery Blvd,"(24.7659472, 46.6391588)","(24.7607916, 46.636143)",0.41,45.30,0,9.95,Blue
77,East Ring Road,"(24.7921447, 46.805914)","(24.6224894, 46.7188421)",4.97,46.10,2,35.51,Blue
78,FAHHAD MOHAMMAD AL JFIRAN STREET,"(24.68896, 46.76417319999999)","(24.6840036, 46.7132541)",1.14,30.06,1,8.91,Blue
84,Imam Malik Road,"(24.8506483, 46.7188421)","(24.7825477, 46.56863670000001)",2.42,52.24,1,22.28,Yellow
87,Jeddah Road,"(24.6942703, 46.64157160000001)","(24.5263166, 46.4387046)",2.34,75.92,2,52.83,Blue
90,Khurais Road,"(24.946473, 46.9999471)","(24.7106093, 46.7623591)",3.50,70.07,2,41.16,Blue
91,King Abdul Aziz Road,"(24.9996923, 46.7285093)","(24.6422095, 46.5499681)",1.77,60.83,2,57.52,Blue
92,King Abdulaziz,"(24.7427455, 46.7450497)","(24.6935528, 46.6929946)",2.52,36.14,1,11.75,Yellow
93,King Abdullah Road,"(24.801193, 46.8204406)","(24.6968763, 46.6222727)",4.19,57.52,1,25.50,Blue
94,King Salman Road,"(24.97692050000003, 46.7237318)","(24.79621499999998, 46.5574488)",0.95,68.24,2,42.18,Blue
95,King Saud,"(24.6933354, 46.7188421)","(24.638759, 46.6457942)",3.14,40.43,1,13.38,Blue
96,Laban Valley,"(24.6575726, 46.6508675)","(24.6016845, 46.563363)",2.98,51.00,1,21.29,Blue
97,Maan Bin Ows,"(24.6320336, 46.8010727)","(24.6273961, 46.7913915)",1.52,45.83,0,7.16,Blue
98,Makkah al-Mukarramah Road,"(24.7201491, 46.7671967)","(24.6656897, 46.6367462)",3.89,48.51,1,16.70,Blue
99,Malham,"(25.1859133, 46.35646819999999)","(25.1446629, 46.3126088)",0.25,38.05,0,7.63,Blue
101,Masafi,"(24.8249208, 46.7484538)","(24.7987016, 46.7084972)",0.05,39.30,0,7.17,Blue
102,Mohamed Ibn Hamd Ibn Faris,"(24.6679326, 46.7478493)","(24.6359973, 46.7285093)",2.46,26.47,0,6.54,Blue
103,Mohammed Ali Jinnah,"(24.8148754, 46.7986522)","(24.7545582, 46.6995133)",0.76,47.61,1,17.84,Blue
104,Nahawand,"(24.584978, 46.7962319)","(24.5632022, 46.75510370000001)",0.09,34.86,0,6.16,Blue
105,No.2,"(24.8184527, 46.6657058)","(24.8152541, 46.6584643)",0.76,48.81,0,6.64,Blue
106,No.509,"(24.9625832, 46.7285093)","(24.699414, 46.574058)",1.40,69.78,2,48.18,Blue
107,Northern Ring Road,"(24.9560346, 47.01452949999999)","(24.7258755, 46.5830947)",2.80,77.95,2,55.00,Blue
108,Olaya Road,"(24.8302126, 46.6995133)","(24.6639052, 46.612626)",2.69,60.91,2,38.20,Blue
109,Omar Al Hajeb,"(24.7854632, 46.8028881)","(24.760707, 46.7590336)",0.37,32.06,0,6.34,Blue
110,Othman Bin Affan Road,"(24.8540833, 46.7285093)","(24.7410088, 46.670534)",4.22,52.66,1,19.09,Blue
114,Qaha,"(24.8094773, 46.7508718)","(24.7984307, 46.712499)",0.56,45.99,0,7.06,Blue
115,Raghdan,"(24.6722289, 46.7345617)","(24.6388126, 46.7019289)",1.46,24.44,1,6.51,Blue
116,Sabta,"(24.76491, 46.6699305)","(24.7191642, 46.6578609)",1.80,41.48,0,7.75,Blue
118,Saeed Bin Amer,"(24.7272521, 46.7727151)","(24.6793498, 46.7581267)",0.12,37.10,0,8.82,Blue
121,Shab uldin Al taj,"(24.78133100000002, 46.6595165)","(24.73717459999997, 46.5755256)",0.82,55.24,0,12.46,Blue
125,Sinan,"(24.6035359, 46.58912)","(24.5978788, 46.58490219999999)",1.45,51.15,0,10.22,Blue
126,Soukh Thi Al Mjaz,"(24.6817475, 46.7546277)","(24.6475414, 46.716127)",0.74,29.46,1,8.52,Blue
129,Tariq Bin Shabab,"(24.6226251, 46.7671967)","(24.5785679, 46.7430136)",1.31,39.14,0,10.27,Blue
131,Wathilan,"(24.5795234, 46.6952861)","(24.5387215, 46.6758154)",0.14,33.44,0,6.40,Blue
132,Western Ring Rd,"(24.7397288, 46.6463975)","(24.5539963, 46.5547852)",3.87,59.43,2,34.84,Blue
133,Yalamlam,"(24.7968728, 46.8017535)","(24.7544746, 46.7894252)",0.33,30.48,1,8.39,Blue
134,Yanbu,"(24.6492832, 46.5861072)","(24.5956169, 46.5018235)",2.78,39.43,1,14.61,Blue
136,أبي العتاهية,"(24.737833, 46.8325494)","(24.7014787, 46.7792927)",0.07,23.38,1,7.74,Blue
138,أبي عبيدة بن مسعود,"(24.7435132, 46.8325494)","(24.7020341, 46.8010727)",0.42,25.31,1,7.18,Blue
139,أبي علي بن الشريف,"(24.5650077, 46.7585045)","(24.5640378, 46.7566151)",0.19,51.93,0,9.73,Blue
144,أحمد الموفق,"(24.6309504, 46.7043448)","(24.5838406, 46.6958899)",0.35,43.89,0,7.88,Yellow
145,أحمد عبدالواحد,"(24.7132022, 46.7652314)","(24.7113442, 46.7638708)",0.89,35.85,0,6.15,Blue
150,أم الزهر,"(24.7438936, 46.6958899)","(24.6915966, 46.6678181)",2.09,38.05,0,9.45,Blue
157,ابن كعب,"(24.7553853, 46.7635685)","(24.7181537, 46.7590336)",0.17,33.30,0,6.38,Blue
161,الأرطاوية,"(26.5400469, 45.3720332)","(26.4802535, 45.3252125)",0.07,48.91,0,7.41,Blue
162,الأسود بن هلال,"(24.76340690000002, 46.6271734)","(24.74446739999997, 46.582252)",0.43,43.87,0,8.13,Blue
164,الأشقر,"(24.9081998, 46.9537969)","(24.8813536, 46.9283108)",0.01,43.10,0,7.44,Blue
166,الأمير فيصل بن عبدالعزيز بن سعود,"(24.6151277, 46.7067607)","(24.6092966, 46.6898516)",2.41,30.83,0,6.52,Orange
167,الأوزاعي,"(24.7533144, 46.80894)","(24.7153136, 46.7716568)",1.04,36.30,0,6.93,Yellow
168,الإسكندراني,"(24.7129533, 46.7762684)","(24.6739252, 46.7448269)",1.05,31.31,0,7.83,Blue
171,الإمام أحمد بن حنبل,"(24.768106, 46.8907119)","(24.6997523, 46.7768732)",0.32,51.14,1,21.08,Blue
172,الإمام بن جرير,"(24.6083, 46.7791414)","(24.6057216, 46.77657079999999)",0.87,44.20,0,7.23,Blue
174,الامام الشافعي,"(24.7318305, 46.815598)","(24.6784302, 46.7817122)",0.35,34.64,1,11.29,Blue
176,الباطن,"(24.7631338, 46.8028881)","(24.642655, 46.7315306)",3.76,45.77,2,22.58,Blue
178,البستان,"(24.7031341, 46.66630929999999)","(24.6959039, 46.6135303)",0.96,44.99,0,9.31,Blue
180,البيت العتيق,"(24.8112938, 46.7445247)","(24.7994054, 46.7188421)",0.91,38.11,0,7.55,Yellow
181,التخصصي,"(24.7577072, 46.6898516)","(24.6509204, 46.6367462)",2.01,47.91,1,22.84,Blue
185,التنهاة,"(24.7570374, 46.5981595)","(24.7397288, 46.58851749999999)",0.14,44.84,0,9.12,Blue
186,الثوابية,"(24.5991424, 46.7285093)","(24.5646728, 46.6801919)",0.24,39.33,0,7.70,Blue
189,الحجل,"(24.7887347, 46.6807956)","(24.7847265, 46.6727974)",1.36,40.98,0,6.49,Orange
190,الحدبه,"(24.6195884, 46.7282071)","(24.5895889, 46.7234866)",2.33,27.43,0,6.98,Blue
191,الحميمة,"(24.6196381, 46.7297178)","(24.5983228, 46.6952861)",1.58,24.02,1,8.46,Blue
192,الحنكة,"(24.7861326, 46.7233733)","(24.7270423, 46.6850215)",1.18,46.32,0,11.41,Blue
193,الحيازين,"(24.7685712, 46.7794439)","(24.6891896, 46.77233709999999)",0.79,36.65,1,13.53,Blue
194,الخزان,"(24.6410953, 46.7260923)","(24.6339923, 46.6880403)",0.74,28.54,1,7.64,Blue
195,الخزرج,"(24.7851293, 46.6850215)","(24.7573837, 46.6596712)",0.65,37.66,0,7.17,Blue
197,الخليفة الناصر لدين الله,"(24.5849552, 46.6343336)","(24.5669688, 46.6210667)",0.20,36.23,0,6.54,Blue
201,الربيع - اليرموك,"(24.8246022, 46.80901840000001)","(24.7913163, 46.7581815)",0.07,29.92,1,10.08,Blue
202,الرسان,"(24.7279212, 46.7947917)","(24.6946911, 46.7618374)",0.01,42.80,0,10.18,Blue
203,الزلفي,"(26.3641879, 44.9210358)","(26.213051, 44.75521089999999)",0.31,56.06,2,28.43,Blue
204,السعادات,"(24.7175308, 46.8558487)","(24.6776424, 46.8168152)",0.34,36.17,0,9.48,Blue
206,السفح,"(24.6130618, 46.720428)","(24.5733974, 46.6964938)",0.50,32.79,1,8.95,Blue
208,السمح بن مالك,"(24.5897615, 46.8567756)","(24.5714292, 46.8252838)",0.62,41.13,0,6.24,Blue
210,السويدي العام,"(24.6055933, 46.7067607)","(24.5807802, 46.6572575)",0.35,44.77,0,8.12,Yellow
213,الشعيرة,"(24.7468638, 46.7478493)","(24.7443783, 46.7114419)",0.32,41.98,0,8.05,Blue
215,الشيخ جابر الأحمد الصباح,"(24.8400346, 46.83012739999999)","(24.7790607, 46.7865516)",1.60,43.25,1,13.08,Blue
216,الشيخ حسن بن حسين بن علي,"(24.8467573, 46.7865516)","(24.7617666, 46.7381783)",1.95,48.61,1,16.18,Blue
217,الشيخ عبدالله المخضوب,"(24.7995141, 46.7094787)","(24.7878151, 46.6897762)",0.26,39.99,0,7.32,Blue
221,الصناعية,"(24.6541091, 46.7619944)","(24.630205, 46.7308212)",1.67,28.50,0,6.50,Blue
222,الضحى,"(24.7706736, 46.7019289)","(24.7356204, 46.6637445)",0.35,35.06,0,8.62,Blue
225,الطريق الدائري الجنوبي الفرعي,"(24.641973, 46.8204406)","(24.5383879, 46.5933382)",6.17,37.70,2,30.18,Blue
226,العباس بن عبدالمطلب,"(24.7841274, 46.7266965)","(24.7663703, 46.6898516)",0.34,45.91,0,8.04,Blue
228,العريجاء,"(24.6361119, 46.6731787)","(24.6126837, 46.6396075)",0.09,32.40,0,6.35,Blue
232,العينة,"(24.6479744, 46.592133)","(24.640628, 46.5710461)",1.66,43.76,0,6.93,Blue
235,الفروثي,"(24.764204, 46.6916631)","(24.7187709, 46.6844178)",1.04,34.67,0,7.41,Yellow
237,الفضول,"(24.7876258, 46.6967957)","(24.7288274, 46.658766)",1.83,47.12,0,10.92,Blue
238,الفكر,"(24.6403854, 46.73696959999999)","(24.6042262, 46.6898516)",4.39,27.72,1,12.66,Orange
239,القادسية,"(24.8395969, 46.8501623)","(24.8001838, 46.7978952)",1.67,39.23,1,11.39,Yellow
240,القاضي,"(24.7454537, 46.7146132)","(24.7408013, 46.7047977)",1.52,38.63,0,7.52,Blue
241,القريات,"(24.8239822, 46.6850215)","(24.8042754, 46.6752873)",2.01,41.74,0,6.83,Blue
242,القضيباء,"(24.8140247, 46.7218629)","(24.7792262, 46.6819652)",0.52,49.36,0,10.64,Blue
243,القطار,"(24.6020912, 46.660878)","(24.5873951, 46.61744909999999)",0.10,28.54,0,6.02,Blue
247,المجاردة,"(24.5676496, 46.7542724)","(24.5644145, 46.7483026)",0.24,59.41,0,14.30,Blue
248,المحرق,"(24.706941, 46.6301119)","(24.7000669, 46.6255891)",0.49,43.99,0,5.98,Blue
253,المضيق,"(24.6975965, 46.7850392)","(24.6385203, 46.7118949)",3.17,29.00,2,13.68,Blue
254,المعيزيلة,"(24.8186427, 46.8597823)","(24.7649743, 46.8156829)",1.26,46.07,1,15.93,Blue
255,الملاح,"(24.6533723, 46.7454314)","(24.6162155, 46.7067607)",4.86,32.97,1,12.67,Yellow
257,الملك سلمان الفرعي,"(24.8558203, 46.6801919)","(24.8423717, 46.6530339)",0.51,56.54,0,7.00,Blue
258,الملك عبدالله,"(24.7598942, 46.7618374)","(24.7040611, 46.7211557)",0.80,44.11,1,12.81,Blue
260,المهندس مساعد العنقري,"(24.7263022, 46.6877384)","(24.7055021, 46.6753627)",1.08,39.65,1,10.85,Blue
265,الواحة,"(24.7519361, 46.7258057)","(24.7213988, 46.68524009999999)",1.22,41.55,0,8.59,Blue
266,الوصلة,"(24.8035774, 46.76749909999999)","(24.7855121, 46.71215919999999)",0.85,34.81,0,9.13,Yellow
268,الوليد بن مسلم,"(24.76329790000003, 46.61907649999999)","(24.74361729999997, 46.5815554)",0.34,44.97,0,8.44,Blue
269,الياسمين,"(24.8430476, 46.6698339)","(24.8006436, 46.6142181)",1.23,36.36,1,9.94,Blue
271,بنت المعتمد,"(24.5963613, 46.5925096)","(24.5935194, 46.5903252)",1.24,49.32,0,11.29,Orange
276,تقي الدين التميمي,"(24.6637775, 46.52589)","(24.6309065, 46.4849839)",1.12,38.93,0,9.01,Yellow
282,جبل عسيب,"(24.8325676, 46.744978)","(24.7791095, 46.6975506)",0.89,48.23,0,12.66,Blue
284,جديدة,"(24.6217074, 46.7164256)","(24.5872201, 46.6928707)",0.89,31.39,0,6.55,Yellow
288,جهام,"(24.808157, 46.7678014)","(24.7739725, 46.7179359)",0.72,36.44,0,8.73,Yellow
289,جويرية بنت الحارث,"(24.7511046, 46.6524305)","(24.7318878, 46.64157160000001)",1.67,46.45,0,7.10,Blue
291,حسين بن سعيد المنوفي,"(24.6675779, 46.7635685)","(24.6640134, 46.7567663)",0.03,46.12,0,7.41,Blue
292,حلبان,"(24.8037367, 46.782922)","(24.7736595, 46.73727179999999)",0.85,32.03,0,8.17,Yellow
293,حليمة السعدية,"(24.6184466, 46.7260923)","(24.6005061, 46.7164256)",3.01,23.41,1,6.22,Orange
294,حمد الخطيب,"(24.6846253, 46.7094787)","(24.6439315, 46.6995133)",1.90,27.43,0,6.63,Blue
296,خارجة بن حذافة,"(24.702937, 46.7442224)","(24.6982062, 46.7049487)",2.78,33.81,0,6.86,Red
297,خالد ابن الوليد,"(24.8177153, 46.7889715)","(24.7236044, 46.7285093)",2.39,44.15,2,22.94,Yellow
300,داود بن الهيثم,"(24.7946905, 46.8373937)","(24.7606591, 46.8107557)",0.77,43.13,0,10.41,Blue
301,دمنهور,"(24.5460718, 46.6813993)","(24.4659922, 46.630715)",0.37,40.29,1,19.53,Blue
303,راجية,"(24.8218292, 46.77324429999999)","(24.8027754, 46.7623591)",0.55,36.41,0,8.89,Blue
307,زهير بن المسيب,"(24.7519855, 46.7986522)","(24.6798075, 46.7647779)",2.29,40.20,1,12.10,Yellow
308,زهير بن حرب,"(24.6253448, 46.7212587)","(24.6057798, 46.6880403)",1.75,23.77,1,8.30,Blue
310,سامطة,"(24.7545783, 46.83622039999999)","(24.7340721, 46.802283)",0.26,53.40,0,9.80,Blue
314,سومطرة,"(24.7753276, 46.6602746)","(24.75078, 46.6165447)",0.67,49.34,0,7.13,Blue
315,شارع أبو ذر الغفاري,"(24.6876224, 46.7762684)","(24.6809226, 46.7572197)",0.31,36.80,0,7.39,Blue
319,شارع أمنة بنت أبي القاسم,"(24.5638385, 46.75827779999999)","(24.5624883, 46.7573709)",0.05,50.63,0,9.58,Blue
321,شارع ابن شداد,"(24.6661731, 46.7312285)","(24.6540629, 46.6768718)",1.87,34.90,0,7.70,Blue
322,شارع الأمير تركي بن عبدالعزيز الثاني,"(24.7596584, 46.6644988)","(24.748831, 46.6409684)",0.18,46.71,0,6.87,Blue
323,شارع الأمير سلطان بن سلمان بن عبدالعزيز,"(24.7275999, 46.6813993)","(24.7154815, 46.6590677)",1.04,32.25,0,5.74,Blue
326,شارع الثلاثين,"(24.7059093, 46.7164256)","(24.6790947, 46.6657058)",2.11,39.05,0,9.01,Blue
327,شارع الحلوة,"(24.7981818, 46.6708358)","(24.7858495, 46.6222727)",0.23,32.23,0,7.58,Blue
328,شارع الزبير بن العوام,"(24.726966, 46.8399674)","(24.6854408, 46.7762684)",1.34,41.56,1,14.21,Yellow
330,شارع الفضل التميمي,"(24.759075, 46.6470008)","(24.7555028, 46.6448894)",2.16,36.69,0,7.43,Blue
331,شارع المدينة المنورة,"(24.6637135, 46.7962319)","(24.5627045, 46.574058)",5.20,52.00,2,34.21,Blue
332,شارع النايفية,"(24.7456243, 46.820138)","(24.7253957, 46.7752099)",0.11,37.28,0,6.48,Blue
338,شارع شرورة,"(24.805822, 46.7659873)","(24.7634044, 46.7405959)",0.04,31.84,0,8.14,Blue
339,شارع طريق الامام محمد بن سعود,"(24.7895371, 46.7526854)","(24.7271816, 46.6270967)",1.84,51.61,1,15.63,Blue
342,شارع على بن أبي طالب,"(24.6805135, 46.7671967)","(24.6134842, 46.7405959)",1.39,45.48,1,16.52,Blue
343,شارع عمر بن عبدالعزيز,"(24.7014787, 46.782922)","(24.6768552, 46.7260923)",0.01,31.41,0,8.10,Blue
344,شارع عنيزة,"(24.7108149, 46.7938116)","(24.6834606, 46.7720347)",0.11,32.18,0,7.11,Blue
346,شارع مؤتة,"(24.7362175, 46.6617832)","(24.6969381, 46.6569558)",0.21,38.13,0,6.23,Blue
347,شارع معاذ بن جبل,"(24.6049838, 46.7786878)","(24.5916431, 46.7702204)",1.30,37.21,0,6.98,Blue
349,شارع وادي حنيفة,"(24.7033408, 46.6807956)","(24.5998153, 46.60298119999999)",2.54,47.36,2,24.02,Yellow
351,شجوى,"(24.5840971, 46.6394604)","(24.5739943, 46.5963138)",1.04,32.03,0,6.82,Yellow
352,صلاح الدين الأيوبي,"(24.7093659, 46.7774781)","(24.6525599, 46.7164256)",1.05,33.74,1,13.93,Yellow
355,طريق أبي بكر الصديق,"(24.9673426, 46.7285093)","(24.6981028, 46.58851749999999)",1.02,63.46,2,50.70,Blue
356,طريق الأمير سطام بن عبدالعزيز,"(24.6587247, 46.6801919)","(24.6158359, 46.6657058)",0.50,27.99,1,8.20,Blue
357,طريق الأمير سعد بن عبدالرحمن الأول,"(24.727772, 46.870105)","(24.6782849, 46.7768732)",0.71,57.76,1,21.97,Blue
360,طريق الامام سعود بن فيصل,"(24.8155263, 46.660878)","(24.773476, 46.5716484)",1.35,52.46,1,18.31,Blue
361,طريق الامير مساعد بن جلوي,"(24.7113313, 46.7188421)","(24.6422095, 46.6946822)",2.47,39.71,1,11.49,Blue
362,طريق الجنادرية,"(24.9690502, 46.8640458)","(24.7798871, 46.7859467)",0.05,53.21,2,29.77,Blue
363,طريق الرياض - الرمحية,"(24.6236475, 46.6989848)","(24.5854023, 46.6870969)",0.36,38.40,0,7.42,Blue
365,طريق العروبة,"(24.7435802, 46.7526854)","(24.6890813, 46.6270967)",3.35,46.11,1,18.35,Blue
367,طريق الملك فهد - الفرعي,"(24.7620395, 46.6898516)","(24.6764758, 46.6463975)",2.24,53.76,1,16.94,Blue
368,طريق الملك فيصل,"(24.6721253, 46.7236754)","(24.6170533, 46.6946822)",3.79,29.86,1,9.52,Blue
370,طريق تركي الأول بن عبدالعزيز آل سعود,"(24.8474334, 46.670534)","(24.6630729, 46.5547852)",0.26,54.92,2,28.87,Blue
373,طريق ديراب,"(24.58994840000003, 46.7055477)","(24.43446389999998, 46.6103736)",2.36,53.96,2,29.67,Yellow
374,طريق طلحة بن عبيدالله,"(24.717821, 46.855564)","(24.6826348, 46.7962319)",0.42,31.88,1,9.29,Yellow
375,طريق عمر بن الخطاب,"(24.6698077, 46.7865516)","(24.6443417, 46.71400920000001)",2.65,27.26,1,9.94,Blue
376,طريق منية,"(24.7542336, 46.7067607)","(24.7256334, 46.6569558)",1.93,39.77,0,7.41,Blue
379,عالية,"(24.7499246, 46.71174389999999)","(24.6996238, 46.6886441)",2.07,33.40,1,9.44,Blue
382,عبداللطيف الخيمي,"(24.6668921, 46.7040428)","(24.6644876, 46.6998152)",2.11,34.25,0,6.06,Orange
383,عبداللطيف بن عبدالملك آل الشيخ,"(24.825001, 46.6198608)","(24.7973643, 46.6053922)",1.43,27.89,0,6.15,Orange
386,عسفات,"(24.7874632, 46.7276406)","(24.7805653, 46.701023)",0.19,42.15,0,9.66,Blue
387,عسيلة,"(24.6110297, 46.6349367)","(24.5715898, 46.58490219999999)",0.47,30.11,1,8.85,Blue
389,عفيف - الحوميات,"(23.0844693, 42.9125976)","(23.0471961, 42.8549193)",0.11,48.28,0,7.36,Blue
391,عمرو بن العاص,"(24.6484974, 46.7073647)","(24.6325151, 46.6750609)",0.30,32.62,0,6.82,Blue
393,فرسان,"(24.7600848, 46.6536372)","(24.6897433, 46.6240816)",1.39,54.22,1,18.23,Blue

In [ ]:
roads_greater_than_50 = df[df['distance_km'] > 50]

# Display the result
roads_greater_than_50[['road_name', 'distance_km']]

                road_name  distance_km
36            Jeddah Road        52.83
38   King Abdul Aziz Road        57.52
51     Northern Ring Road        55.00
155   طريق أبي بكر الصديق        50.70

In [ ]:
# r_sh = [29,88,92,109,140,158,308,359,361,362,381,406]
# df.loc[r_sh]

In [ ]:
# df.drop([140, 308, 359, 362, 381], inplace=True)

In [ ]:
df.shape

(226, 8)

In [ ]:
df.head()

,road_name,Start_point,End_point,delay_min,speed_kmh,duration_in_traffic_min,distance_km,traffic_condition
0,'Al Sabe,"(24.598009, 46.5957488)","(24.5954907, 46.5925096)",1.34,49.99,0,11.73,Blue
1,110 ممر,"(24.594892, 46.6403652)","(24.571468, 46.5812872)",1.18,34.51,0,8.40,Yellow
2,3rd Roundabout,"(24.6652373, 46.7968369)","(24.6631823, 46.7870053)",0.02,48.38,0,6.09,Blue
5,Abdulaziz Al Fereh,"(24.6746147, 46.73819719999999)","(24.586689, 46.6373493)",0.96,33.72,2,19.60,Blue
7,Abi Hasain Al Hanbali,"(24.8022123, 46.6638953)","(24.7837499, 46.6243831)",0.10,34.61,0,8.82,Blue

In [ ]:
df.isna().sum()
df.dropna(inplace=True)

In [ ]:
# df.drop(columns=['outside_riyadh'],inplace=True)

In [ ]:
df.shape

(226, 8)

In [ ]:
# df.to_csv('formatted_traffic_data(11).csv', index=False)

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Select numerical columns for clustering
columns_for_clustering = ['delay_min', 'speed_kmh', 'duration_in_traffic_min', 'distance_km']

# Data Preprocessing: Standardizing the numerical columns
scaler = StandardScaler()
scaled_data = scaler.fit_df(df[columns_for_clustering])

# Apply K-Means clustering with an arbitrary number of clusters (let's start with 3 clusters)
kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(scaled_data)

# Plot the clustering results to visualize how data is grouped
plt.scatter(scaled_data[:, 1], scaled_data[:, 2], c=df['cluster'], cmap='viridis', s=50)
plt.title('K-Means Clustering of Traffic Data')
plt.xlabel('Speed (scaled)')
plt.ylabel('Duration in Traffic (scaled)')
plt.show()

# Show the first few rows with the cluster assignments
print(df[['road_name', 'delay_min', 'speed_kmh', 'duration_in_traffic_min', 'distance_km', 'cluster']].head())

AttributeError: 'StandardScaler' object has no attribute 'fit_df'

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# First, we need to extract latitude and longitude from the Start_point and End_point
df['start_latitude'] = df['Start_point'].apply(lambda x: float(x.strip('()').split(',')[0]))
df['start_longitude'] = df['Start_point'].apply(lambda x: float(x.strip('()').split(',')[1]))
df['end_latitude'] = df['End_point'].apply(lambda x: float(x.strip('()').split(',')[0]))
df['end_longitude'] = df['End_point'].apply(lambda x: float(x.strip('()').split(',')[1]))

# Select the relevant columns for clustering (road size and direction)
columns_for_clustering = ['start_latitude', 'start_longitude', 'end_latitude', 'end_longitude', 'distance_km']

# Data Preprocessing: Standardizing the columns
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[columns_for_clustering])

# Apply K-Means clustering, using 3 clusters as an initial guess
kmeans = KMeans(n_clusters=3, random_state=42)
df['cluster'] = kmeans.fit_predict(scaled_data)

# Plotting the clustering results based on the start and end points (road direction)
plt.scatter(scaled_data[:, 0], scaled_data[:, 1], c=df['cluster'], cmap='viridis', s=50)
plt.title('K-Means Clustering of Roads Based on Size and Direction')
plt.xlabel('Start Latitude (scaled)')
plt.ylabel('Start Longitude (scaled)')
plt.show()

# Show the first few rows with the cluster assignments
print(df[['road_name', 'start_latitude', 'start_longitude', 'end_latitude', 'end_longitude', 'distance_km', 'cluster']].head())

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

# Function to calculate direction of the road based on start and end points
def calculate_direction(start, end):
    # Convert string tuples to numeric values
    start_lat, start_lon = eval(start)
    end_lat, end_lon = eval(end)

    # Calculate the difference between the start and end points
    delta_lat = end_lat - start_lat
    delta_lon = end_lon - start_lon

    # Use arctan2 to calculate the angle of the road
    angle = np.arctan2(delta_lat, delta_lon)

    # Convert the angle from radians to degrees
    angle_degrees = np.degrees(angle)

    return angle_degrees

# Apply the function to calculate the direction for each road
df['direction'] = df.apply(lambda row: calculate_direction(row['Start_point'], row['End_point']), axis=1)

# Now we select road characteristics for clustering: distance and direction
columns_for_clustering = ['distance_km', 'direction']

# Data Preprocessing: Standardizing the numerical columns
scaler = StandardScaler()
scaled_data = scaler.fit_transform(df[columns_for_clustering])

# Apply K-Means clustering with 3 clusters (you can adjust this)
kmeans = KMeans(n_clusters=3, random_state=42)
df['road_cluster'] = kmeans.fit_predict(scaled_data)

# Show the first few rows with the road cluster assignments
print(df[['road_name', 'Start_point', 'End_point', 'distance_km', 'direction', 'road_cluster']])

# Plot the clustering results to visualize how roads are grouped
plt.scatter(scaled_data[:, 0], scaled_data[:, 1], c=df['road_cluster'], cmap='viridis', s=50)
plt.title('K-Means Clustering of Roads Based on Characteristics')
plt.xlabel('Distance (scaled)')
plt.ylabel('Direction (scaled)')
plt.show()